# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class AgentCodeSnippetSampleCode(UncheckedBaseModel):
    non_stream: str = pydantic.Field()
    """
    SDK sample that creates a turn without streaming.
    """

    stream: str = pydantic.Field()
    """
    SDK sample that streams turn events.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
