# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .sandbox_capability import SandboxCapability
from .settings_capability import SettingsCapability
from .skill_capability import SkillCapability


class CapabilitiesData(UncheckedBaseModel):
    sandbox: SandboxCapability
    settings: SettingsCapability
    skill: SkillCapability

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
