# This file was auto-generated by Fern from our API Definition.

import typing

from .user_mcp_auth_continue_event import UserMcpAuthContinueEvent
from .user_tool_approval_event import UserToolApprovalEvent
from .user_tool_approval_policy_event import UserToolApprovalPolicyEvent
from .user_tool_response_event import UserToolResponseEvent

CreateTurnEventResponseDataItem = typing.Union[
    UserMcpAuthContinueEvent, UserToolApprovalEvent, UserToolApprovalPolicyEvent, UserToolResponseEvent
]
