# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .create_turn_event_response_data_item import CreateTurnEventResponseDataItem


class CreateTurnEventResponse(UncheckedBaseModel):
    data: typing.List[CreateTurnEventResponseDataItem] = pydantic.Field()
    """
    Events with server-minted `id` and `created_at`, in request order.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
