# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .daytona_sandbox_environment_resources_gpu_type import DaytonaSandboxEnvironmentResourcesGpuType


class DaytonaSandboxEnvironmentResources(UncheckedBaseModel):
    cpu: typing.Optional[float] = pydantic.Field(default=None)
    """
    CPU allocation in cores.
    """

    disk: typing.Optional[float] = pydantic.Field(default=None)
    """
    Disk allocation in GiB.
    """

    gpu: typing.Optional[float] = pydantic.Field(default=None)
    """
    GPU allocation in Daytona GPU units.
    """

    gpu_type: typing.Optional[DaytonaSandboxEnvironmentResourcesGpuType] = pydantic.Field(default=None)
    """
    Preferred GPU type, or an ordered fallback list.
    """

    memory: typing.Optional[float] = pydantic.Field(default=None)
    """
    Memory allocation in GiB.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
