# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .resource_permission import ResourcePermission


class ListPermissionsResponse(UncheckedBaseModel):
    data: typing.Dict[str, typing.List[ResourcePermission]] = pydantic.Field()
    """
    Permissions granted to the caller, keyed by resource id. Missing or inaccessible ids are `[]`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
