# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ModelMessageUsageInputTokensBreakdown(UncheckedBaseModel):
    harness: int = pydantic.Field()
    """
    Tokens attributed to harness system framing.
    """

    instructions: int = pydantic.Field()
    """
    Tokens attributed to agent instructions.
    """

    messages: int = pydantic.Field()
    """
    Tokens attributed to conversation messages.
    """

    skills: int = pydantic.Field()
    """
    Tokens attributed to skill instructions.
    """

    tool_definitions: int = pydantic.Field()
    """
    Tokens attributed to tool schemas.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
