# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .daytona_sandbox_provider_auth import DaytonaSandboxProviderAuth


class SandboxProviderManifest(UncheckedBaseModel):
    auth: DaytonaSandboxProviderAuth
    auto_archive_interval_in_minutes: int = pydantic.Field()
    """
    Minutes before Daytona auto-archives the sandbox (0 disables).
    """

    auto_delete_interval_in_minutes: int = pydantic.Field()
    """
    Minutes before Daytona auto-deletes the sandbox (0 disables).
    """

    auto_stop_interval_in_minutes: int = pydantic.Field()
    """
    Minutes of idle time before Daytona auto-stops the sandbox (0 disables).
    """

    exec_timeout_ms: int = pydantic.Field()
    """
    Default sandbox command exec timeout in milliseconds.
    """

    type: typing.Literal["daytona"] = pydantic.Field(default="daytona")
    """
    Daytona sandbox provider.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
