# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .created_by_subject import CreatedBySubject
from .schedule_run_status import ScheduleRunStatus


class ScheduleRun(UncheckedBaseModel):
    created_at: dt.datetime
    created_by_subject: CreatedBySubject
    id: str
    name: str
    reason: typing.Optional[str] = None
    schedule_id: str
    scheduled_for: dt.datetime
    status: ScheduleRunStatus
    triggered_at: typing.Optional[dt.datetime] = None
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
