# This file was auto-generated by Fern from our API Definition.

import typing

from .session_agent_inline import SessionAgentInline
from .session_agent_reference import SessionAgentReference

SessionAgent = typing.Union[SessionAgentInline, SessionAgentReference]
