# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .approval_decision import ApprovalDecision


class UserToolApprovalEvent(UncheckedBaseModel):
    approval: ApprovalDecision
    thread_id: str = pydantic.Field()
    """
    Thread that owns the pending tool call.
    """

    tool_call_id: str = pydantic.Field()
    """
    Tool call id being approved or denied.
    """

    type: typing.Literal["user.tool_approval"] = "user.tool_approval"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
