# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .user_message_content import UserMessageContent


class UserMessage(UncheckedBaseModel):
    content: UserMessageContent = pydantic.Field()
    """
    Plain string or structured text/file content parts.
    """

    type: typing.Literal["user.message"] = "user.message"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
