// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfiguredMcpServerAuth } from "./ConfiguredMcpServerAuth.js";

export const CatalogMcpServer: core.serialization.ObjectSchema<
    serializers.CatalogMcpServer.Raw,
    TrueHarness.CatalogMcpServer
> = core.serialization.object({
    auth: ConfiguredMcpServerAuth.optional(),
    name: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace CatalogMcpServer {
    export interface Raw {
        auth?: ConfiguredMcpServerAuth.Raw | null;
        name: string;
        url: string;
    }
}
