// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfiguredMcpServerAuth } from "./ConfiguredMcpServerAuth.js";
import { McpServerType } from "./McpServerType.js";

export const CatalogMcpServer: core.serialization.ObjectSchema<
    serializers.CatalogMcpServer.Raw,
    TrueForge.CatalogMcpServer
> = core.serialization.object({
    auth: ConfiguredMcpServerAuth.optional(),
    logo: core.serialization.string().optional(),
    name: core.serialization.string(),
    type: McpServerType,
    url: core.serialization.string(),
});

export declare namespace CatalogMcpServer {
    export interface Raw {
        auth?: ConfiguredMcpServerAuth.Raw | null;
        logo?: string | null;
        name: string;
        type: McpServerType.Raw;
        url: string;
    }
}
