// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ContextManagementConfigCompaction } from "./ContextManagementConfigCompaction.js";
import { LargeToolResponseConfig } from "./LargeToolResponseConfig.js";

export const ContextManagementConfig: core.serialization.ObjectSchema<
    serializers.ContextManagementConfig.Raw,
    TrueHarness.ContextManagementConfig
> = core.serialization.object({
    compaction: ContextManagementConfigCompaction.optional(),
    largeToolResponse: core.serialization.property("large_tool_response", LargeToolResponseConfig.optional()),
});

export declare namespace ContextManagementConfig {
    export interface Raw {
        compaction?: ContextManagementConfigCompaction.Raw | null;
        large_tool_response?: LargeToolResponseConfig.Raw | null;
    }
}
