// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Agent } from "./Agent.js";

export const CreateAgentResponse: core.serialization.ObjectSchema<
    serializers.CreateAgentResponse.Raw,
    TrueForge.CreateAgentResponse
> = core.serialization.object({
    data: Agent,
    sessionUpdatedAt: core.serialization.property("session_updated_at", core.serialization.string().optional()),
});

export declare namespace CreateAgentResponse {
    export interface Raw {
        data: Agent.Raw;
        session_updated_at?: string | null;
    }
}
