// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetCapabilitiesResponseData } from "./GetCapabilitiesResponseData.js";

export const GetCapabilitiesResponse: core.serialization.ObjectSchema<
    serializers.GetCapabilitiesResponse.Raw,
    TrueHarness.GetCapabilitiesResponse
> = core.serialization.object({
    data: GetCapabilitiesResponseData,
});

export declare namespace GetCapabilitiesResponse {
    export interface Raw {
        data: GetCapabilitiesResponseData.Raw;
    }
}
