// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetLegacyCapabilitiesResponseDataSandbox } from "./GetLegacyCapabilitiesResponseDataSandbox.js";

export const GetLegacyCapabilitiesResponseData: core.serialization.ObjectSchema<
    serializers.GetLegacyCapabilitiesResponseData.Raw,
    TrueHarness.GetLegacyCapabilitiesResponseData
> = core.serialization.object({
    sandbox: GetLegacyCapabilitiesResponseDataSandbox,
});

export declare namespace GetLegacyCapabilitiesResponseData {
    export interface Raw {
        sandbox: GetLegacyCapabilitiesResponseDataSandbox.Raw;
    }
}
