// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CatalogMcpServer } from "./CatalogMcpServer.js";

export const GetMcpServerCatalogResponse: core.serialization.ObjectSchema<
    serializers.GetMcpServerCatalogResponse.Raw,
    TrueHarness.GetMcpServerCatalogResponse
> = core.serialization.object({
    data: core.serialization.list(CatalogMcpServer),
});

export declare namespace GetMcpServerCatalogResponse {
    export interface Raw {
        data: CatalogMcpServer.Raw[];
    }
}
