// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfiguredSkill } from "./ConfiguredSkill.js";

export const ListSkillsResponse: core.serialization.ObjectSchema<
    serializers.ListSkillsResponse.Raw,
    TrueForge.ListSkillsResponse
> = core.serialization.object({
    data: core.serialization.list(ConfiguredSkill),
});

export declare namespace ListSkillsResponse {
    export interface Raw {
        data: ConfiguredSkill.Raw[];
    }
}
