// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ListMcpToolsResponse: core.serialization.ObjectSchema<
    serializers.ListMcpToolsResponse.Raw,
    TrueHarness.ListMcpToolsResponse
> = core.serialization.object({
    data: core.serialization.list(core.serialization.record(core.serialization.string(), core.serialization.unknown())),
});

export declare namespace ListMcpToolsResponse {
    export interface Raw {
        data: Record<string, unknown>[];
    }
}
