// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpAuthorizeResponseStatus } from "./McpAuthorizeResponseStatus.js";

export const McpAuthorizeResponse: core.serialization.ObjectSchema<
    serializers.McpAuthorizeResponse.Raw,
    TrueHarness.McpAuthorizeResponse
> = core.serialization.object({
    authUrl: core.serialization.property("auth_url", core.serialization.string().optional()),
    status: McpAuthorizeResponseStatus,
});

export declare namespace McpAuthorizeResponse {
    export interface Raw {
        auth_url?: string | null;
        status: McpAuthorizeResponseStatus.Raw;
    }
}
