// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const McpServerAuthSettings: core.serialization.ObjectSchema<
    serializers.McpServerAuthSettings.Raw,
    TrueHarness.McpServerAuthSettings
> = core.serialization.object({
    type: core.serialization.stringLiteral("dcr"),
});

export declare namespace McpServerAuthSettings {
    export interface Raw {
        type: "dcr";
    }
}
