// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AnthropicModelProvider } from "./AnthropicModelProvider.js";
import { CustomModelProvider } from "./CustomModelProvider.js";
import { OpenAiModelProvider } from "./OpenAiModelProvider.js";

export const ModelProvider: core.serialization.Schema<serializers.ModelProvider.Raw, TrueHarness.ModelProvider> =
    core.serialization.undiscriminatedUnion([AnthropicModelProvider, CustomModelProvider, OpenAiModelProvider]);

export declare namespace ModelProvider {
    export type Raw = AnthropicModelProvider.Raw | CustomModelProvider.Raw | OpenAiModelProvider.Raw;
}
