// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CallerSuppliedModelProvider } from "./CallerSuppliedModelProvider.js";
import { WellKnownModelProvider } from "./WellKnownModelProvider.js";

export const ModelProvider: core.serialization.Schema<serializers.ModelProvider.Raw, TrueForge.ModelProvider> =
    core.serialization.undiscriminatedUnion([WellKnownModelProvider, CallerSuppliedModelProvider]);

export declare namespace ModelProvider {
    export type Raw = WellKnownModelProvider.Raw | CallerSuppliedModelProvider.Raw;
}
