// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ModelEntryApiKeyOpenaiApi: core.serialization.Schema<
    serializers.ModelEntryApiKeyOpenaiApi.Raw,
    TrueHarness.ModelEntryApiKeyOpenaiApi
> = core.serialization.enum_(["responses", "chat"]);

export declare namespace ModelEntryApiKeyOpenaiApi {
    export type Raw = "responses" | "chat";
}
