// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ModelEntryOneProvider: core.serialization.Schema<
    serializers.ModelEntryOneProvider.Raw,
    TrueHarness.ModelEntryOneProvider
> = core.serialization.enum_(["anthropic", "google"]);

export declare namespace ModelEntryOneProvider {
    export type Raw = "anthropic" | "google";
}
