// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ModelEntryApiKeyProvider: core.serialization.Schema<
    serializers.ModelEntryApiKeyProvider.Raw,
    TrueHarness.ModelEntryApiKeyProvider
> = core.serialization.enum_(["openai-compatible", "litellm", "truefoundry"]);

export declare namespace ModelEntryApiKeyProvider {
    export type Raw = "openai-compatible" | "litellm" | "truefoundry";
}
