// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ModelListProvider } from "./ModelListProvider.js";
import { ModelProperties } from "./ModelProperties.js";

export const Model: core.serialization.ObjectSchema<serializers.Model.Raw, TrueForge.Model> = core.serialization.object(
    {
        modelId: core.serialization.property("model_id", core.serialization.string()),
        name: core.serialization.string(),
        properties: ModelProperties,
        provider: ModelListProvider,
    },
);

export declare namespace Model {
    export interface Raw {
        model_id: string;
        name: string;
        properties: ModelProperties.Raw;
        provider: ModelListProvider.Raw;
    }
}
