// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ResponseFormatOne: core.serialization.ObjectSchema<
    serializers.ResponseFormatOne.Raw,
    TrueHarness.ResponseFormatOne
> = core.serialization.object({
    type: core.serialization.stringLiteral("json_object"),
});

export declare namespace ResponseFormatOne {
    export interface Raw {
        type: "json_object";
    }
}
