// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ResponseFormatJsonObject: core.serialization.ObjectSchema<
    serializers.ResponseFormatJsonObject.Raw,
    TrueForge.ResponseFormatJsonObject
> = core.serialization
    .object({
        type: core.serialization.stringLiteral("json_object"),
    })
    .passthrough();

export declare namespace ResponseFormatJsonObject {
    export interface Raw {
        type: "json_object";
        [key: string]: any;
    }
}
