// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AskUserQuestionsConfig } from "./AskUserQuestionsConfig.js";
import { ContextManagementConfig } from "./ContextManagementConfig.js";
import { DynamicSubAgentsConfig } from "./DynamicSubAgentsConfig.js";
import { GenerativeUiConfig } from "./GenerativeUiConfig.js";
import { SandboxConfig } from "./SandboxConfig.js";

export const RuntimeConfig: core.serialization.ObjectSchema<serializers.RuntimeConfig.Raw, TrueForge.RuntimeConfig> =
    core.serialization.object({
        askUserQuestions: core.serialization.property("ask_user_questions", AskUserQuestionsConfig.optional()),
        contextManagement: core.serialization.property("context_management", ContextManagementConfig.optional()),
        dynamicSubAgents: core.serialization.property("dynamic_sub_agents", DynamicSubAgentsConfig.optional()),
        generativeUi: core.serialization.property("generative_ui", GenerativeUiConfig.optional()),
        iterationLimit: core.serialization.property("iteration_limit", core.serialization.number().optional()),
        sandbox: SandboxConfig.optional(),
    });

export declare namespace RuntimeConfig {
    export interface Raw {
        ask_user_questions?: AskUserQuestionsConfig.Raw | null;
        context_management?: ContextManagementConfig.Raw | null;
        dynamic_sub_agents?: DynamicSubAgentsConfig.Raw | null;
        generative_ui?: GenerativeUiConfig.Raw | null;
        iteration_limit?: number | null;
        sandbox?: SandboxConfig.Raw | null;
    }
}
