// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SandboxArtifact: core.serialization.ObjectSchema<
    serializers.SandboxArtifact.Raw,
    TrueHarness.SandboxArtifact
> = core.serialization.object({
    label: core.serialization.string(),
    path: core.serialization.string(),
});

export declare namespace SandboxArtifact {
    export interface Raw {
        label: string;
        path: string;
    }
}
