// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SandboxProviderResponseBuildMetadata: core.serialization.ObjectSchema<
    serializers.SandboxProviderResponseBuildMetadata.Raw,
    TrueForge.SandboxProviderResponseBuildMetadata
> = core.serialization.object({
    buildRef: core.serialization.property("build_ref", core.serialization.string()),
    imageUri: core.serialization.property("image_uri", core.serialization.string()),
});

export declare namespace SandboxProviderResponseBuildMetadata {
    export interface Raw {
        build_ref: string;
        image_uri: string;
    }
}
