// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DaytonaSandboxProvider } from "./DaytonaSandboxProvider.js";
import { SandboxImage } from "./SandboxImage.js";

export const SandboxProviderResponse: core.serialization.ObjectSchema<
    serializers.SandboxProviderResponse.Raw,
    TrueForge.SandboxProviderResponse
> = core.serialization
    .object({
        image: SandboxImage,
    })
    .extend(DaytonaSandboxProvider);

export declare namespace SandboxProviderResponse {
    export interface Raw extends DaytonaSandboxProvider.Raw {
        image: SandboxImage.Raw;
    }
}
