// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SandboxImageBuildStatus } from "./SandboxImageBuildStatus.js";

export const SandboxImage: core.serialization.ObjectSchema<serializers.SandboxImage.Raw, TrueForge.SandboxImage> =
    core.serialization.object({
        buildRef: core.serialization.property("build_ref", core.serialization.string()),
        buildStatus: core.serialization.property("build_status", SandboxImageBuildStatus),
        tag: core.serialization.string(),
    });

export declare namespace SandboxImage {
    export interface Raw {
        build_ref: string;
        build_status: SandboxImageBuildStatus.Raw;
        tag: string;
    }
}
