// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TextContent: core.serialization.ObjectSchema<serializers.TextContent.Raw, TrueForge.TextContent> =
    core.serialization.object({
        text: core.serialization.string(),
        type: core.serialization.stringLiteral("text"),
    });

export declare namespace TextContent {
    export interface Raw {
        text: string;
        type: "text";
    }
}
