// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnInputItem } from "./TurnInputItem.js";
import { TurnStateRunning } from "./TurnStateRunning.js";

export const TurnCreatedEvent: core.serialization.ObjectSchema<
    serializers.TurnCreatedEvent.Raw,
    TrueHarness.TurnCreatedEvent
> = core.serialization.object({
    type: core.serialization.stringLiteral("turn.created"),
    id: core.serialization.string(),
    turnId: core.serialization.property("turn_id", core.serialization.string()),
    previousTurnId: core.serialization.property("previous_turn_id", core.serialization.string().nullable()),
    input: core.serialization.list(TurnInputItem).optional(),
    state: TurnStateRunning,
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    threadId: core.serialization.property("thread_id", core.serialization.string().nullable()),
});

export declare namespace TurnCreatedEvent {
    export interface Raw {
        type: "turn.created";
        id: string;
        turn_id: string;
        previous_turn_id?: string | null;
        input?: TurnInputItem.Raw[] | null;
        state: TurnStateRunning.Raw;
        created_at: string;
        thread_id?: string | null;
    }
}
