// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FinishReason } from "./FinishReason.js";
import { ModelMessageUsage } from "./ModelMessageUsage.js";
import { ToolCall } from "./ToolCall.js";
import { TurnStateDoneOutputContent } from "./TurnStateDoneOutputContent.js";

export const TurnStateDoneOutput: core.serialization.ObjectSchema<
    serializers.TurnStateDoneOutput.Raw,
    TrueHarness.TurnStateDoneOutput
> = core.serialization.object({
    content: TurnStateDoneOutputContent.optionalNullable(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    finishReason: core.serialization.property("finish_reason", FinishReason.optionalNullable()),
    id: core.serialization.string(),
    name: core.serialization.string().optional(),
    reasoningContent: core.serialization.property("reasoning_content", core.serialization.string().optional()),
    refusal: core.serialization.string().optionalNullable(),
    threadId: core.serialization.property("thread_id", core.serialization.string()),
    toolCalls: core.serialization.property("tool_calls", core.serialization.list(ToolCall).optional()),
    type: core.serialization.stringLiteral("model.message"),
    usage: ModelMessageUsage.optional(),
});

export declare namespace TurnStateDoneOutput {
    export interface Raw {
        content?: (TurnStateDoneOutputContent.Raw | null | undefined) | null;
        created_at: string;
        finish_reason?: (FinishReason.Raw | null | undefined) | null;
        id: string;
        name?: string | null;
        reasoning_content?: string | null;
        refusal?: (string | null | undefined) | null;
        thread_id: string;
        tool_calls?: ToolCall.Raw[] | null;
        type: "model.message";
        usage?: ModelMessageUsage.Raw | null;
    }
}
