// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnStateErrorMetrics } from "./TurnStateErrorMetrics.js";

export const TurnStateError: core.serialization.ObjectSchema<serializers.TurnStateError.Raw, TrueForge.TurnStateError> =
    core.serialization.object({
        completedAt: core.serialization.property("completed_at", core.serialization.string()),
        message: core.serialization.string(),
        metrics: TurnStateErrorMetrics.optional(),
        status: core.serialization.stringLiteral("error"),
    });

export declare namespace TurnStateError {
    export interface Raw {
        completed_at: string;
        message: string;
        metrics?: TurnStateErrorMetrics.Raw | null;
        status: "error";
    }
}
