// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { SandboxProviderManifest } from "../../../../../../types/SandboxProviderManifest.js";

export const PutSandboxProviderRequest: core.serialization.Schema<
    serializers.settings.PutSandboxProviderRequest.Raw,
    TrueForge.settings.PutSandboxProviderRequest
> = core.serialization.object({
    manifest: SandboxProviderManifest,
});

export declare namespace PutSandboxProviderRequest {
    export interface Raw {
        manifest: SandboxProviderManifest.Raw;
    }
}
