// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../index.js";

/**
 * @example
 *     {
 *         agentId: "agent_id",
 *         manifest: {
 *             cron: "cron",
 *             task: "task"
 *         },
 *         name: "name"
 *     }
 */
export interface CreateScheduleRequest {
    agentId: string;
    manifest: TrueForge.ScheduleManifest;
    name: TrueForge.ResourceName;
}
