// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSchedulesRequest {
    /** Page size. Defaults to 25 */
    limit?: number;
    /** Opaque token from a previous response `next_page_token`. */
    pageToken?: string;
    /** Filter by one or more agent names (comma-separated). When set, at least one name is required. */
    agentNames?: string;
}
