// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface AgentCodeSnippets {
    /** Public base URL for the TrueForge SDK `baseUrl`. */
    baseUrl: string;
    snippets: TrueForge.AgentCodeSnippet[];
}
