// This file was auto-generated by Fern from our API Definition.

export interface AvailableSkill {
    /** Concise guidance for when the agent should use the skill. */
    description: string;
    /** Display label when it differs from name (registry). */
    displayName?: string;
    /** Skill name. */
    name: string;
    /** Repo where the skill is registered. */
    skillRepoName?: string;
    /** Version number. */
    version?: number;
}
