// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface AvailableModel {
    /** Upstream, provider-specific identifier sent to the provider API. */
    modelId: string;
    /** Fully qualified name `provider_name/model_name`, e.g. "openai/gpt-5-6-sol". Unique within a tenant. */
    name: string;
    properties: TrueForge.ModelProperties;
    provider: TrueForge.AvailableModelProvider;
}
