// This file was auto-generated by Fern from our API Definition.

export interface DaytonaSandboxEnvironmentNetworking {
    /** Comma-separated allowed domains. */
    domainAllowList?: string;
    /** Comma-separated allowed CIDR network addresses. */
    networkAllowList?: string;
    /** Block all outbound network access. */
    networkBlockAll?: boolean;
    /** Outbound HTTP(S) proxy URL. */
    outboundProxyUrl?: string;
}
