// This file was auto-generated by Fern from our API Definition.

export interface GetCapabilitiesResponseDataSkill {
    /** Whether skills are available. False when sandbox is not enabled (skills require a sandbox). */
    enabled: boolean;
    /** Present when skills are disabled. Explains why. */
    reason?: string;
}
