// This file was auto-generated by Fern from our API Definition.

export interface ModelMessageUsageInputTokensBreakdown {
    /** Tokens attributed to harness system framing. */
    harness: number;
    /** Tokens attributed to agent instructions. */
    instructions: number;
    /** Tokens attributed to conversation messages. */
    messages: number;
    /** Tokens attributed to skill instructions. */
    skills: number;
    /** Tokens attributed to tool schemas. */
    toolDefinitions: number;
}
