// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface Model {
    /** Model FQN: `provider/model`, e.g. `openai/gpt-5.2`. */
    name: string;
    params?: TrueForge.ModelParams;
}
