// This file was auto-generated by Fern from our API Definition.

/**
 * Defaults to 'auto' (chain to session last turn). Use 'none' for a new root turn.
 */
export type PreviousTurnIdInput = "auto" | "none" | string;
