// This file was auto-generated by Fern from our API Definition.

/**
 * JSON Schema payload. Extra provider fields are allowed.
 */
export interface ResponseFormatJsonSchemaJsonSchema {
    /** Optional schema description for the model. */
    description?: string;
    /** Schema name sent to the provider. */
    name: string;
    /** JSON Schema object for the response. */
    schema?: Record<string, unknown>;
    /** When true, ask the provider to enforce the schema strictly. */
    strict?: boolean | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
