// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface SandboxEnvironmentManifest {
    image: TrueForge.DaytonaSandboxEnvironmentImage;
    lifecycle?: TrueForge.DaytonaSandboxEnvironmentLifecycle;
    networking?: TrueForge.DaytonaSandboxEnvironmentNetworking;
    /** Must match the configured sandbox provider name/type. */
    provider: "daytona";
    resources?: TrueForge.DaytonaSandboxEnvironmentResources;
    /** Map of sandbox env var name to an existing Daytona organization secret name. */
    secrets?: Record<string, string>;
    /** Daytona sandbox environment. */
    type: "daytona";
}
