// This file was auto-generated by Fern from our API Definition.

export interface SandboxConfig {
    /** Give the agent a sandbox. Required for skills and Code Mode. */
    enabled: boolean;
    /** Name of a configured sandbox environment to use. Must exist when set. */
    environmentName?: string;
    /** Allow downloading agent-produced files via the turn download endpoint. Default: true. */
    fileDownloads?: boolean;
}
