// This file was auto-generated by Fern from our API Definition.

export interface SandboxCreatedEvent {
    /** ISO 8601 event timestamp. */
    createdAt: string;
    /** Sandbox environment name when created with one; omit for provider defaults. */
    environment?: string;
    /** Unique identifier for the event (monotonic ULID). */
    id: string;
    /** Provider sandbox id. */
    sandboxId: string;
    /** Always null — sandbox is session-scoped. */
    threadId: string | null;
    type: "sandbox.created";
}
