// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface Schedule {
    agentName: TrueForge.ResourceName;
    createdAt: Date;
    createdBy: string;
    id: string;
    manifest: TrueForge.ScheduleManifest;
    name: TrueForge.ResourceName;
    updatedAt: Date;
}
