// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

/**
 * How this session was created (e.g. a schedule run). Null for interactive sessions.
 */
export type SessionSource = TrueForge.SessionSourceSchedule | null;
