// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface Session {
    agent: TrueForge.SessionAgent;
    /** ISO 8601 creation timestamp. */
    createdAt: string;
    createdBySubject: TrueForge.CreatedBySubject;
    /** Unique session id. */
    id: string;
    metadata: TrueForge.SessionMetadata;
    metrics: TrueForge.SessionMetrics;
    /** When true, any subject in the tenant may read this session and its turns/events by id. */
    shared: boolean;
    source: TrueForge.SessionSource | null;
    /** Optional human-readable title; null until set. */
    title: string | null;
    /** ISO 8601 last-update timestamp. */
    updatedAt: string;
}
