// This file was auto-generated by Fern from our API Definition.

export const SessionMetricsGraphUnit = {
    Count: "count",
    Usd: "$",
} as const;
export type SessionMetricsGraphUnit = (typeof SessionMetricsGraphUnit)[keyof typeof SessionMetricsGraphUnit];
