// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ToolApprovalPolicyItem {
    action: TrueForge.ToolApprovalPolicyAllowSession;
    /** Tool name on that server. */
    name: string;
    /** MCP server name. */
    serverName: string;
}
