// This file was auto-generated by Fern from our API Definition.

export interface TrueFoundrySandboxProvider {
    /** Default sandbox command exec timeout in milliseconds. */
    execTimeoutMs: number;
    /** Cluster-internal NATS WebSocket bridge URL. */
    natsBridgeUrl: string;
    /** TFY sandbox HTTP server URL. */
    serverUrl: string;
    type: "truefoundry";
}
