// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface TurnStateDone {
    /** ISO 8601 time when the turn reached a terminal state. */
    completedAt: string;
    metrics?: TrueForge.TurnMetrics;
    /** Final `model.message` for the turn, or null when the turn ended paused without a final message. */
    output: TrueForge.ModelMessageEvent | null;
    /** Pending actions (`tool.approval_required`, `tool.response_required`, `mcp.auth_required`); empty when none. */
    requiredActions: TrueForge.ActionRequiredEvent[];
    status: "done";
}
