// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface UserToolApprovalPolicyEvent {
    /** ISO 8601 event timestamp. */
    createdAt: string;
    /** Unique identifier for the event (monotonic ULID). */
    id: string;
    /** One or more (server_name, name) policy entries. */
    policies: TrueForge.ToolApprovalPolicyItem[];
    type: "user.tool_approval_policy";
}
