// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../src/api/index";
import { TrueForge } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SandboxEnvironmentsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    created_by_subject: {
                        subject_display_name: "subject_display_name",
                        subject_id: "subject_id",
                        subject_type: "subject_type",
                    },
                    description: "description",
                    id: "id",
                    manifest: { image: { ref: "ref", type: "docker" }, provider: "daytona", type: "daytona" },
                    name: "name",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: { limit: 1, next_page_token: "next_page_token", previous_page_token: "previous_page_token" },
        };

        server
            .mockEndpoint({ once: false })
            .get("/api/v1/sandbox-environments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdBySubject: {
                        subjectDisplayName: "subject_display_name",
                        subjectId: "subject_id",
                        subjectType: "subject_type",
                    },
                    description: "description",
                    id: "id",
                    manifest: {
                        image: {
                            ref: "ref",
                            type: "docker",
                        },
                        provider: "daytona",
                        type: "daytona",
                    },
                    name: "name",
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
            pagination: {
                limit: 1,
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
            },
        };
        const page = await client.sandboxEnvironments.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.list();
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.list();
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "ref", type: "docker" }, provider: "daytona", type: "daytona" },
            name: "name",
        };
        const rawResponseBody = {
            data: {
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                description: "description",
                id: "id",
                manifest: {
                    image: { ref: "ref", type: "docker" },
                    provider: "daytona",
                    secrets: { key: "value" },
                    type: "daytona",
                },
                name: "name",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandboxEnvironments.create({
            manifest: {
                image: {
                    ref: "ref",
                    type: "docker",
                },
                provider: "daytona",
                type: "daytona",
            },
            name: "name",
        });
        expect(response).toEqual({
            data: {
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                description: "description",
                id: "id",
                manifest: {
                    image: {
                        ref: "ref",
                        type: "docker",
                    },
                    provider: "daytona",
                    secrets: {
                        key: "value",
                    },
                    type: "daytona",
                },
                name: "name",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "x", type: "docker" }, provider: "daytona", type: "daytona" },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.create({
                manifest: {
                    image: {
                        ref: "x",
                        type: "docker",
                    },
                    provider: "daytona",
                    type: "daytona",
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "x", type: "docker" }, provider: "daytona", type: "daytona" },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.create({
                manifest: {
                    image: {
                        ref: "x",
                        type: "docker",
                    },
                    provider: "daytona",
                    type: "daytona",
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "x", type: "docker" }, provider: "daytona", type: "daytona" },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.create({
                manifest: {
                    image: {
                        ref: "x",
                        type: "docker",
                    },
                    provider: "daytona",
                    type: "daytona",
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.ConflictError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "x", type: "docker" }, provider: "daytona", type: "daytona" },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.create({
                manifest: {
                    image: {
                        ref: "x",
                        type: "docker",
                    },
                    provider: "daytona",
                    type: "daytona",
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                description: "description",
                id: "id",
                manifest: {
                    image: { ref: "ref", type: "docker" },
                    provider: "daytona",
                    secrets: { key: "value" },
                    type: "daytona",
                },
                name: "name",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments/sandbox_environment_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandboxEnvironments.get("sandbox_environment_id");
        expect(response).toEqual({
            data: {
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                description: "description",
                id: "id",
                manifest: {
                    image: {
                        ref: "ref",
                        type: "docker",
                    },
                    provider: "daytona",
                    secrets: {
                        key: "value",
                    },
                    type: "daytona",
                },
                name: "name",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments/sandbox_environment_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.get("sandbox_environment_id");
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments/sandbox_environment_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.get("sandbox_environment_id");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "ref", type: "docker" }, provider: "daytona", type: "daytona" },
        };
        const rawResponseBody = {
            data: {
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                description: "description",
                id: "id",
                manifest: {
                    image: { ref: "ref", type: "docker" },
                    provider: "daytona",
                    secrets: { key: "value" },
                    type: "daytona",
                },
                name: "name",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments/sandbox_environment_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandboxEnvironments.update("sandbox_environment_id", {
            manifest: {
                image: {
                    ref: "ref",
                    type: "docker",
                },
                provider: "daytona",
                type: "daytona",
            },
        });
        expect(response).toEqual({
            data: {
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                description: "description",
                id: "id",
                manifest: {
                    image: {
                        ref: "ref",
                        type: "docker",
                    },
                    provider: "daytona",
                    secrets: {
                        key: "value",
                    },
                    type: "daytona",
                },
                name: "name",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "x", type: "docker" }, provider: "daytona", type: "daytona" },
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments/sandbox_environment_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.update("sandbox_environment_id", {
                manifest: {
                    image: {
                        ref: "x",
                        type: "docker",
                    },
                    provider: "daytona",
                    type: "daytona",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "x", type: "docker" }, provider: "daytona", type: "daytona" },
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments/sandbox_environment_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.update("sandbox_environment_id", {
                manifest: {
                    image: {
                        ref: "x",
                        type: "docker",
                    },
                    provider: "daytona",
                    type: "daytona",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "x", type: "docker" }, provider: "daytona", type: "daytona" },
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments/sandbox_environment_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.update("sandbox_environment_id", {
                manifest: {
                    image: {
                        ref: "x",
                        type: "docker",
                    },
                    provider: "daytona",
                    type: "daytona",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { image: { ref: "x", type: "docker" }, provider: "daytona", type: "daytona" },
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments/sandbox_environment_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.update("sandbox_environment_id", {
                manifest: {
                    image: {
                        ref: "x",
                        type: "docker",
                    },
                    provider: "daytona",
                    type: "daytona",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.UnprocessableEntityError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/sandbox_environment_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandboxEnvironments.delete("sandbox_environment_id");
        expect(response).toEqual({});
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/sandbox_environment_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.delete("sandbox_environment_id");
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/sandbox_environment_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.delete("sandbox_environment_id");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/sandbox_environment_id")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.delete("sandbox_environment_id");
        }).rejects.toThrow(TrueForgeTypes.ConflictError);
    });
});
