// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../src/api/index";
import { TrueForge } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SandboxEnvironmentsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    created_by_subject: {
                        subject_display_name: "subject_display_name",
                        subject_id: "subject_id",
                        subject_type: "subject_type",
                    },
                    description: "description",
                    id: "id",
                    lifecycle_stage: "active",
                    manifest: { image: { build_script: "set -ex\npip install httpx\n", type: "build" }, name: "name" },
                    name: "name",
                    status: "pending",
                    status_reason: "status_reason",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: { limit: 1, next_page_token: "next_page_token", previous_page_token: "previous_page_token" },
        };

        server
            .mockEndpoint({ once: false })
            .get("/api/v1/sandbox-environments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdBySubject: {
                        subjectDisplayName: "subject_display_name",
                        subjectId: "subject_id",
                        subjectType: "subject_type",
                    },
                    description: "description",
                    id: "id",
                    lifecycleStage: "active",
                    manifest: {
                        image: {
                            buildScript: "set -ex\npip install httpx\n",
                            type: "build",
                        },
                        name: "name",
                    },
                    name: "name",
                    status: "pending",
                    statusReason: "status_reason",
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
            pagination: {
                limit: 1,
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
            },
        };
        const page = await client.sandboxEnvironments.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.list();
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.list();
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("create_or_update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { manifest: { name: "name" } };
        const rawResponseBody = {
            data: {
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                description: "description",
                id: "id",
                lifecycle_stage: "active",
                manifest: {
                    description: "description",
                    environment_variables: { key: "value" },
                    image: { build_script: "set -ex\npip install httpx\n", type: "build" },
                    name: "name",
                },
                name: "name",
                status: "pending",
                status_reason: "status_reason",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandboxEnvironments.createOrUpdate({
            manifest: {
                name: "name",
            },
        });
        expect(response).toEqual({
            data: {
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                description: "description",
                id: "id",
                lifecycleStage: "active",
                manifest: {
                    description: "description",
                    environmentVariables: {
                        key: "value",
                    },
                    image: {
                        buildScript: "set -ex\npip install httpx\n",
                        type: "build",
                    },
                    name: "name",
                },
                name: "name",
                status: "pending",
                statusReason: "status_reason",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("create_or_update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { manifest: { name: "xy" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.createOrUpdate({
                manifest: {
                    name: "xy",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("create_or_update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { manifest: { name: "xy" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.createOrUpdate({
                manifest: {
                    name: "xy",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("create_or_update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { manifest: { name: "xy" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.createOrUpdate({
                manifest: {
                    name: "xy",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.ConflictError);
    });

    test("create_or_update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { manifest: { name: "xy" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.createOrUpdate({
                manifest: {
                    name: "xy",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.UnprocessableEntityError);
    });

    test("create_or_update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { manifest: { name: "xy" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/sandbox-environments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.createOrUpdate({
                manifest: {
                    name: "xy",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.BadGatewayError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                description: "description",
                id: "id",
                lifecycle_stage: "active",
                manifest: {
                    description: "description",
                    environment_variables: { key: "value" },
                    image: { build_script: "set -ex\npip install httpx\n", type: "build" },
                    name: "name",
                },
                name: "name",
                status: "pending",
                status_reason: "status_reason",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandboxEnvironments.get("name");
        expect(response).toEqual({
            data: {
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                description: "description",
                id: "id",
                lifecycleStage: "active",
                manifest: {
                    description: "description",
                    environmentVariables: {
                        key: "value",
                    },
                    image: {
                        buildScript: "set -ex\npip install httpx\n",
                        type: "build",
                    },
                    name: "name",
                },
                name: "name",
                status: "pending",
                statusReason: "status_reason",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.get("name");
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.get("name");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandboxEnvironments.delete("name");
        expect(response).toEqual({});
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.delete("name");
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.delete("name");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.delete("name");
        }).rejects.toThrow(TrueForgeTypes.ConflictError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.delete("name");
        }).rejects.toThrow(TrueForgeTypes.UnprocessableEntityError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/sandbox-environments/name")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sandboxEnvironments.delete("name");
        }).rejects.toThrow(TrueForgeTypes.BadGatewayError);
    });
});
