// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../src/api/index";
import { TrueForge } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SkillsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { data: [{ description: "description", metadata: { key: "value" }, name: "name" }] };

        server.mockEndpoint().get("/api/v1/skills").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.skills.list();
        expect(response).toEqual({
            data: [
                {
                    description: "description",
                    metadata: {
                        key: "value",
                    },
                    name: "name",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server.mockEndpoint().get("/api/v1/skills").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.skills.list();
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("list_versions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [{ description: "description", display_name: "display_name", name: "name", version: 1 }],
        };

        server
            .mockEndpoint()
            .get("/api/v1/skills/versions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.listVersions({
            name: "name",
        });
        expect(response).toEqual({
            data: [
                {
                    description: "description",
                    displayName: "display_name",
                    name: "name",
                    version: 1,
                },
            ],
        });
    });

    test("list_versions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/skills/versions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.listVersions({
                name: "x",
            });
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });
});
