# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.get_capabilities_response import GetCapabilitiesResponse
from .raw_client import AsyncRawServerClient, RawServerClient


class ServerClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawServerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawServerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawServerClient
        """
        return self._raw_client

    def get_capabilities(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetCapabilitiesResponse:
        """
        Report optional runtime capabilities available for this tenant.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCapabilitiesResponse
            Server capabilities.

        Examples
        --------
        from trueforge_sdk import TrueForge

        client = TrueForge(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.server.get_capabilities()
        """
        _response = self._raw_client.get_capabilities(request_options=request_options)
        return _response.data


class AsyncServerClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawServerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawServerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawServerClient
        """
        return self._raw_client

    async def get_capabilities(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCapabilitiesResponse:
        """
        Report optional runtime capabilities available for this tenant.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCapabilitiesResponse
            Server capabilities.

        Examples
        --------
        import asyncio

        from trueforge_sdk import AsyncTrueForge

        client = AsyncTrueForge(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.server.get_capabilities()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_capabilities(request_options=request_options)
        return _response.data
