import type { SemanticTokens, ThemePreset } from '../types.js';

export type PresetTokens = {
  light: SemanticTokens;
  dark: SemanticTokens;
};

const trueforge: PresetTokens = {
  light: {
    sidebarBg: '#FAFAFA',
    topbarBg: '#FFFFFF',
    primaryBg: '#FFFFFF',
    secondaryBg: '#F4F4F5',
    border: '#E4E4E7',
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    inputBoxBg: '#FAFAFA',
    inputBorder: '#E4E4E7',
    textPrimary: '#18181B',
    textSecondary: '#62626A',
    cardBg: '#FFFFFF',
    dropdownSelectedItemBg: '#F1F1F2',
    dropdownSelectedItemText: '#18181B',
    userMessageBg: '#6366F1',
    userMessageText: '#FFFFFF',
    assistantMessageBg: 'transparent',
    assistantMessageText: '#18181B',
    primaryButtonBg: '#6366F1',
    primaryButtonHover: '#4F46E5',
    primaryButtonText: '#FFFFFF',
    secondaryButtonBg: '#FAFAFA',
    secondaryButtonHover: '#E4E4E7',
    secondaryButtonText: '#18181B',
    ghostButtonBg: 'transparent',
    ghostButtonHover: '#F4F4F5',
    ghostButtonText: '#18181B',
    successBg: '#16A34A',
    successText: '#FFFFFF',
    failureBg: '#EF4444',
    failureText: '#FFFFFF',
    warningBg: '#D97706',
    warningText: '#FFFFFF',
    focusRing: '#E4E4E7',
    radius: '0.5rem',
    composerRadius: '1.5rem',
    overlay: 'rgb(24 24 27 / 0.5)',
    shadowColor: '#18181B',
    scrollbarThumb: '#62626A',
  },
  dark: {
    sidebarBg: '#18181B',
    topbarBg: '#18181B',
    primaryBg: '#1F1F22',
    secondaryBg: '#27272A',
    border: '#343439',
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    inputBoxBg: '#27272A',
    inputBorder: '#343439',
    textPrimary: '#FDFDFD',
    textSecondary: '#A1A1AA',
    cardBg: '#18181B',
    dropdownSelectedItemBg: '#3F3F46',
    dropdownSelectedItemText: '#FDFDFD',
    userMessageBg: '#6366F1',
    userMessageText: '#FFFFFF',
    assistantMessageBg: 'transparent',
    assistantMessageText: '#FDFDFD',
    primaryButtonBg: '#6366F1',
    primaryButtonHover: '#4F46E5',
    primaryButtonText: '#FFFFFF',
    secondaryButtonBg: '#27272A',
    secondaryButtonHover: '#343439',
    secondaryButtonText: '#FDFDFD',
    ghostButtonBg: 'transparent',
    ghostButtonHover: '#343439',
    ghostButtonText: '#FDFDFD',
    successBg: '#4ADE80',
    successText: '#052E16',
    failureBg: '#EF4444',
    failureText: '#FFFFFF',
    warningBg: '#FBBF24',
    warningText: '#422006',
    focusRing: '#6366F1',
    radius: '0.5rem',
    composerRadius: '1.5rem',
    overlay: 'rgb(0 0 0 / 0.7)',
    shadowColor: '#000000',
    scrollbarThumb: '#A1A1AA',
  },
};

/** assistant-ui's Claude clone: warm cream surfaces, serif type, and orange actions. */
const claude: PresetTokens = {
  light: {
    sidebarBg: '#f0ece0',
    topbarBg: '#f0ece0',
    primaryBg: '#f0ece0',
    secondaryBg: '#e5e0d6',
    border: '#e5e0d6',
    fontFamily: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
    inputBoxBg: '#ffffff',
    inputBorder: '#e5e0d6',
    textPrimary: '#1a1a18',
    textSecondary: '#5b5950',
    cardBg: '#ffffff',
    dropdownSelectedItemBg: '#1a1a180d',
    dropdownSelectedItemText: '#1a1a18',
    userMessageBg: '#e5e0d6',
    userMessageText: '#1a1a18',
    assistantMessageBg: 'transparent',
    assistantMessageText: '#1a1a18',
    primaryButtonBg: '#c96442',
    primaryButtonHover: '#b55738',
    primaryButtonText: '#ffffff',
    secondaryButtonBg: '#e5e0d6',
    secondaryButtonHover: '#d9d3c8',
    secondaryButtonText: '#1a1a18',
    ghostButtonBg: 'transparent',
    ghostButtonHover: '#1a1a180d',
    ghostButtonText: '#1a1a18',
    successBg: '#15803d',
    successText: '#ffffff',
    failureBg: '#d03b3b',
    failureText: '#ffffff',
    warningBg: '#b45309',
    warningText: '#ffffff',
    focusRing: '#c96442',
    radius: '1rem',
    composerRadius: '1rem',
    overlay: 'rgb(9 9 11 / 0.5)',
    shadowColor: '#1a1a18',
    scrollbarThumb: '#5b5950',
  },
  dark: {
    sidebarBg: '#2b2a27',
    topbarBg: '#2b2a27',
    primaryBg: '#2b2a27',
    secondaryBg: '#1f1e1b',
    border: '#3d3a35',
    fontFamily: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
    inputBoxBg: '#1f1e1b',
    inputBorder: '#3d3a35',
    textPrimary: '#eeeeee',
    textSecondary: '#a3a098',
    cardBg: '#1f1e1b',
    dropdownSelectedItemBg: '#ffffff0d',
    dropdownSelectedItemText: '#eeeeee',
    userMessageBg: '#3d3a35',
    userMessageText: '#eeeeee',
    assistantMessageBg: 'transparent',
    assistantMessageText: '#eeeeee',
    primaryButtonBg: '#c96442',
    primaryButtonHover: '#b55738',
    primaryButtonText: '#ffffff',
    secondaryButtonBg: '#3d3a35',
    secondaryButtonHover: '#4a4640',
    secondaryButtonText: '#eeeeee',
    ghostButtonBg: 'transparent',
    ghostButtonHover: '#ffffff0d',
    ghostButtonText: '#eeeeee',
    successBg: '#4ade80',
    successText: '#052e16',
    failureBg: '#d03b3b',
    failureText: '#ffffff',
    warningBg: '#fbbf24',
    warningText: '#422006',
    focusRing: '#c96442',
    radius: '1rem',
    composerRadius: '1rem',
    overlay: 'rgb(0 0 0 / 0.7)',
    shadowColor: '#000000',
    scrollbarThumb: '#a3a098',
  },
};

/** assistant-ui's ChatGPT clone: stark surfaces and high-contrast controls. */
const chatgpt: PresetTokens = {
  light: {
    sidebarBg: '#ffffff',
    topbarBg: '#ffffff',
    primaryBg: '#ffffff',
    secondaryBg: '#f9f9f9',
    border: '#e5e5e5',
    fontFamily: '"GeistSans", "GeistSans Fallback", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    inputBoxBg: '#ffffff',
    inputBorder: '#e5e5e5',
    textPrimary: '#0d0d0d',
    textSecondary: '#5d5d5d',
    cardBg: '#ffffff',
    dropdownSelectedItemBg: '#00000012',
    dropdownSelectedItemText: '#0d0d0d',
    userMessageBg: '#e9e9e980',
    userMessageText: '#0d0d0d',
    assistantMessageBg: 'transparent',
    assistantMessageText: '#0d0d0d',
    primaryButtonBg: '#0d0d0d',
    primaryButtonHover: '#2a2a2a',
    primaryButtonText: '#ffffff',
    secondaryButtonBg: '#ececec',
    secondaryButtonHover: '#e0e0e0',
    secondaryButtonText: '#0d0d0d',
    ghostButtonBg: 'transparent',
    ghostButtonHover: '#00000012',
    ghostButtonText: '#0d0d0d',
    successBg: '#16a34a',
    successText: '#ffffff',
    failureBg: '#ff002a',
    failureText: '#ffffff',
    warningBg: '#d97706',
    warningText: '#ffffff',
    focusRing: '#0d0d0d',
    radius: '1.5rem',
    composerRadius: '1.75rem',
    overlay: 'rgb(9 9 11 / 0.5)',
    shadowColor: '#0d0d0d',
    scrollbarThumb: '#5d5d5d',
  },
  dark: {
    sidebarBg: '#000000',
    topbarBg: '#000000',
    primaryBg: '#000000',
    secondaryBg: '#303030',
    border: '#ffffff26',
    fontFamily: '"GeistSans", "GeistSans Fallback", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    inputBoxBg: '#212121',
    inputBorder: '#ffffff26',
    textPrimary: '#ececec',
    textSecondary: '#cdcdcd',
    cardBg: '#212121',
    dropdownSelectedItemBg: '#ffffff26',
    dropdownSelectedItemText: '#ffffff',
    userMessageBg: '#323232',
    userMessageText: '#ffffff',
    assistantMessageBg: 'transparent',
    assistantMessageText: '#ececec',
    primaryButtonBg: '#ffffff',
    primaryButtonHover: '#e8e8e8',
    primaryButtonText: '#0d0d0d',
    secondaryButtonBg: '#303030',
    secondaryButtonHover: '#3a3a3a',
    secondaryButtonText: '#ffffff',
    ghostButtonBg: 'transparent',
    ghostButtonHover: '#ffffff26',
    ghostButtonText: '#ececec',
    successBg: '#4ade80',
    successText: '#052e16',
    failureBg: '#ff002a',
    failureText: '#ffffff',
    warningBg: '#fbbf24',
    warningText: '#422006',
    focusRing: '#ffffff',
    radius: '1.5rem',
    composerRadius: '1.75rem',
    overlay: 'rgb(0 0 0 / 0.7)',
    shadowColor: '#000000',
    scrollbarThumb: '#cdcdcd',
  },
};

/** Gemini's Material surfaces and blue action accents. */
const gemini: PresetTokens = {
  light: {
    sidebarBg: '#fdfcfc',
    topbarBg: '#fdfcfc',
    primaryBg: '#fdfcfc',
    secondaryBg: '#f8fafd',
    border: '#dadce0',
    fontFamily: '"GeistSans", "GeistSans Fallback", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    inputBoxBg: '#ffffff',
    inputBorder: '#dadce0',
    textPrimary: '#1f1f1f',
    textSecondary: '#444746',
    cardBg: '#ffffff',
    dropdownSelectedItemBg: '#e9eef6',
    dropdownSelectedItemText: '#1f1f1f',
    userMessageBg: '#f3f6fc',
    userMessageText: '#1f1f1f',
    assistantMessageBg: 'transparent',
    assistantMessageText: '#1f1f1f',
    primaryButtonBg: '#1f3b9b',
    primaryButtonHover: '#1a3285',
    primaryButtonText: '#ffffff',
    secondaryButtonBg: '#e8eaed',
    secondaryButtonHover: '#dadce0',
    secondaryButtonText: '#1f1f1f',
    ghostButtonBg: 'transparent',
    ghostButtonHover: '#e9eef6',
    ghostButtonText: '#1f1f1f',
    successBg: '#188038',
    successText: '#ffffff',
    failureBg: '#b3261e',
    failureText: '#ffffff',
    warningBg: '#b06000',
    warningText: '#ffffff',
    focusRing: '#1f3b9b',
    radius: '1rem',
    composerRadius: '2rem',
    overlay: 'rgb(9 9 11 / 0.5)',
    shadowColor: '#1f1f1f',
    scrollbarThumb: '#444746',
  },
  dark: {
    sidebarBg: '#0c0c0c',
    topbarBg: '#0c0c0c',
    primaryBg: '#0c0c0c',
    secondaryBg: '#1b1b1b',
    border: '#3c4043',
    fontFamily: '"GeistSans", "GeistSans Fallback", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    inputBoxBg: '#1e1f20',
    inputBorder: '#3c4043',
    textPrimary: '#e3e3e3',
    textSecondary: '#c4c7c5',
    cardBg: '#1e1f20',
    dropdownSelectedItemBg: '#282a2c',
    dropdownSelectedItemText: '#e3e3e3',
    userMessageBg: '#222327',
    userMessageText: '#e3e3e3',
    assistantMessageBg: 'transparent',
    assistantMessageText: '#e3e3e3',
    primaryButtonBg: '#a8c7fa',
    primaryButtonHover: '#8ab4f8',
    primaryButtonText: '#062e6f',
    secondaryButtonBg: '#2b2c2e',
    secondaryButtonHover: '#353638',
    secondaryButtonText: '#e3e3e3',
    ghostButtonBg: 'transparent',
    ghostButtonHover: '#282a2c',
    ghostButtonText: '#e3e3e3',
    successBg: '#81c995',
    successText: '#0d3b1e',
    failureBg: '#f2b8b5',
    failureText: '#601410',
    warningBg: '#fdd663',
    warningText: '#4a3000',
    focusRing: '#a8c7fa',
    radius: '1rem',
    composerRadius: '2rem',
    overlay: 'rgb(0 0 0 / 0.7)',
    shadowColor: '#000000',
    scrollbarThumb: '#c4c7c5',
  },
};

export const PRESETS: Record<ThemePreset, PresetTokens> = {
  trueforge,
  claude,
  chatgpt,
  gemini,
};

export function resolvePresetTokens(preset: ThemePreset | undefined, mode: 'light' | 'dark'): SemanticTokens {
  return PRESETS[preset ?? 'trueforge'][mode];
}
