// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateSessionRequest {
    agent?: TrueForge.SessionAgentSpecBody;
    metadata?: TrueForge.SessionMetadata;
    /** When true, any subject in the tenant may read this session and its turns/events by id. */
    shared?: boolean;
    /** Human-readable session title. */
    title?: string;
}
