// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateSessionRequest {
    agent?: TrueForge.SessionAgentSpecBody;
    metadata?: TrueForge.SessionMetadata;
    /** Human-readable session title. */
    title?: string;
}
