// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { McpServerDcrAuth } from "../../../../../types/McpServerDcrAuth.js";
import { McpServerHeaderAuth } from "../../../../../types/McpServerHeaderAuth.js";

export const McpServerManifestAuth: core.serialization.Schema<
    serializers.settings.McpServerManifestAuth.Raw,
    TrueForge.settings.McpServerManifestAuth
> = core.serialization.undiscriminatedUnion([McpServerDcrAuth, McpServerHeaderAuth]);

export declare namespace McpServerManifestAuth {
    export type Raw = McpServerDcrAuth.Raw | McpServerHeaderAuth.Raw;
}
