// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ResourceName } from "./ResourceName.js";

export const AvailableSkill: core.serialization.ObjectSchema<serializers.AvailableSkill.Raw, TrueForge.AvailableSkill> =
    core.serialization.object({
        description: core.serialization.string(),
        name: ResourceName,
    });

export declare namespace AvailableSkill {
    export interface Raw {
        description: string;
        name: ResourceName.Raw;
    }
}
