// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CatalogSkillType } from "./CatalogSkillType.js";
import { ResourceName } from "./ResourceName.js";

export const CatalogSkill: core.serialization.ObjectSchema<serializers.CatalogSkill.Raw, TrueForge.CatalogSkill> =
    core.serialization.object({
        description: core.serialization.string(),
        name: ResourceName,
        path: core.serialization.string().optional(),
        ref: core.serialization.string(),
        type: CatalogSkillType,
        url: core.serialization.string(),
    });

export declare namespace CatalogSkill {
    export interface Raw {
        description: string;
        name: ResourceName.Raw;
        path?: string | null;
        ref: string;
        type: CatalogSkillType.Raw;
        url: string;
    }
}
