// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CatalogSandboxProviderDomainProtocol } from "./CatalogSandboxProviderDomainProtocol.js";

export const CatalogSandboxProviderDomain: core.serialization.ObjectSchema<
    serializers.CatalogSandboxProviderDomain.Raw,
    TrueForge.CatalogSandboxProviderDomain
> = core.serialization.object({
    domain: core.serialization.string(),
    execTimeoutMs: core.serialization.property("exec_timeout_ms", core.serialization.number()),
    protocol: CatalogSandboxProviderDomainProtocol.optional(),
    type: core.serialization.stringLiteral("opensandbox"),
});

export declare namespace CatalogSandboxProviderDomain {
    export interface Raw {
        domain: string;
        exec_timeout_ms: number;
        protocol?: CatalogSandboxProviderDomainProtocol.Raw | null;
        type: "opensandbox";
    }
}
