// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ResourceName } from "./ResourceName.js";
import { WebSearchProviderManifest } from "./WebSearchProviderManifest.js";

export const ConfiguredWebSearchProvider: core.serialization.ObjectSchema<
    serializers.ConfiguredWebSearchProvider.Raw,
    TrueForge.ConfiguredWebSearchProvider
> = core.serialization.object({
    manifest: WebSearchProviderManifest,
    name: ResourceName,
});

export declare namespace ConfiguredWebSearchProvider {
    export interface Raw {
        manifest: WebSearchProviderManifest.Raw;
        name: ResourceName.Raw;
    }
}
