// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CreatedTurnInboundEvent } from "./CreatedTurnInboundEvent.js";

export const CreateTurnInboundEventResponse: core.serialization.ObjectSchema<
    serializers.CreateTurnInboundEventResponse.Raw,
    TrueForge.CreateTurnInboundEventResponse
> = core.serialization.object({
    data: core.serialization.list(CreatedTurnInboundEvent),
});

export declare namespace CreateTurnInboundEventResponse {
    export interface Raw {
        data: CreatedTurnInboundEvent.Raw[];
    }
}
