// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserToolApprovalEvent } from "./UserToolApprovalEvent.js";
import { UserToolApprovalPolicyEvent } from "./UserToolApprovalPolicyEvent.js";
import { UserToolResponseEvent } from "./UserToolResponseEvent.js";

export const CreatedTurnInboundEvent: core.serialization.Schema<
    serializers.CreatedTurnInboundEvent.Raw,
    TrueForge.CreatedTurnInboundEvent
> = core.serialization.undiscriminatedUnion([
    UserToolApprovalEvent,
    UserToolApprovalPolicyEvent,
    UserToolResponseEvent,
]);

export declare namespace CreatedTurnInboundEvent {
    export type Raw = UserToolApprovalEvent.Raw | UserToolApprovalPolicyEvent.Raw | UserToolResponseEvent.Raw;
}
