// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DaytonaGpuType: core.serialization.Schema<serializers.DaytonaGpuType.Raw, TrueForge.DaytonaGpuType> =
    core.serialization.enum_(["H100", "H200", "RTX-PRO-6000", "RTX-4090", "RTX-5090"]);

export declare namespace DaytonaGpuType {
    export type Raw = "H100" | "H200" | "RTX-PRO-6000" | "RTX-4090" | "RTX-5090";
}
