// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeleteSkillResponse: core.serialization.ObjectSchema<
    serializers.DeleteSkillResponse.Raw,
    TrueForge.DeleteSkillResponse
> = core.serialization.object({});

export declare namespace DeleteSkillResponse {
    export type Raw = {};
}
