// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeleteScheduleResponse: core.serialization.ObjectSchema<
    serializers.DeleteScheduleResponse.Raw,
    TrueForge.DeleteScheduleResponse
> = core.serialization.object({});

export declare namespace DeleteScheduleResponse {
    export type Raw = {};
}
