// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GenerativeUiConfig: core.serialization.ObjectSchema<
    serializers.GenerativeUiConfig.Raw,
    TrueForge.GenerativeUiConfig
> = core.serialization.object({
    enabled: core.serialization.boolean().optional(),
});

export declare namespace GenerativeUiConfig {
    export interface Raw {
        enabled?: boolean | null;
    }
}
