// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Me } from "./Me.js";

export const GetMeResponse: core.serialization.ObjectSchema<serializers.GetMeResponse.Raw, TrueForge.GetMeResponse> =
    core.serialization.object({
        data: Me,
    });

export declare namespace GetMeResponse {
    export interface Raw {
        data: Me.Raw;
    }
}
