// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SandboxEnvironment } from "./SandboxEnvironment.js";

export const GetSandboxEnvironmentResponse: core.serialization.ObjectSchema<
    serializers.GetSandboxEnvironmentResponse.Raw,
    TrueForge.GetSandboxEnvironmentResponse
> = core.serialization.object({
    data: SandboxEnvironment,
});

export declare namespace GetSandboxEnvironmentResponse {
    export interface Raw {
        data: SandboxEnvironment.Raw;
    }
}
