// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SessionMetricsChartResponse } from "./SessionMetricsChartResponse.js";

export const GetSessionMetricsChartResponse: core.serialization.ObjectSchema<
    serializers.GetSessionMetricsChartResponse.Raw,
    TrueForge.GetSessionMetricsChartResponse
> = core.serialization.object({
    data: SessionMetricsChartResponse,
});

export declare namespace GetSessionMetricsChartResponse {
    export interface Raw {
        data: SessionMetricsChartResponse.Raw;
    }
}
