// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CatalogSandboxProvider } from "./CatalogSandboxProvider.js";

export const GetSandboxProviderCatalogResponse: core.serialization.ObjectSchema<
    serializers.GetSandboxProviderCatalogResponse.Raw,
    TrueForge.GetSandboxProviderCatalogResponse
> = core.serialization.object({
    data: core.serialization.list(CatalogSandboxProvider),
});

export declare namespace GetSandboxProviderCatalogResponse {
    export interface Raw {
        data: CatalogSandboxProvider.Raw[];
    }
}
