// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const InputTokensCompactionTrigger: core.serialization.ObjectSchema<
    serializers.InputTokensCompactionTrigger.Raw,
    TrueForge.InputTokensCompactionTrigger
> = core.serialization.object({
    type: core.serialization.stringLiteral("input_tokens"),
    value: core.serialization.number(),
});

export declare namespace InputTokensCompactionTrigger {
    export interface Raw {
        type: "input_tokens";
        value: number;
    }
}
