// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfiguredWebSearchProvider } from "./ConfiguredWebSearchProvider.js";

export const ListWebSearchProvidersResponse: core.serialization.ObjectSchema<
    serializers.ListWebSearchProvidersResponse.Raw,
    TrueForge.ListWebSearchProvidersResponse
> = core.serialization.object({
    data: core.serialization.list(ConfiguredWebSearchProvider),
});

export declare namespace ListWebSearchProvidersResponse {
    export interface Raw {
        data: ConfiguredWebSearchProvider.Raw[];
    }
}
