// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AvailableSkill } from "./AvailableSkill.js";

export const ListAvailableSkillsResponse: core.serialization.ObjectSchema<
    serializers.ListAvailableSkillsResponse.Raw,
    TrueForge.ListAvailableSkillsResponse
> = core.serialization.object({
    data: core.serialization.list(AvailableSkill),
});

export declare namespace ListAvailableSkillsResponse {
    export interface Raw {
        data: AvailableSkill.Raw[];
    }
}
