// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RemoteMcpServerManifest } from "./RemoteMcpServerManifest.js";
import { TrueFoundryMcpServerManifest } from "./TrueFoundryMcpServerManifest.js";

export const McpServerManifest: core.serialization.Schema<
    serializers.McpServerManifest.Raw,
    TrueForge.McpServerManifest
> = core.serialization.undiscriminatedUnion([RemoteMcpServerManifest, TrueFoundryMcpServerManifest]);

export declare namespace McpServerManifest {
    export type Raw = RemoteMcpServerManifest.Raw | TrueFoundryMcpServerManifest.Raw;
}
