// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetMeSubject } from "./GetMeSubject.js";
import { MeSessionType } from "./MeSessionType.js";

export const Me: core.serialization.ObjectSchema<serializers.Me.Raw, TrueForge.Me> = core.serialization.object({
    roles: core.serialization.list(core.serialization.string()),
    subject: GetMeSubject,
    tenantId: core.serialization.property("tenant_id", core.serialization.string()),
    type: MeSessionType,
});

export declare namespace Me {
    export interface Raw {
        roles: string[];
        subject: GetMeSubject.Raw;
        tenant_id: string;
        type: MeSessionType.Raw;
    }
}
