// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MeSessionType: core.serialization.Schema<serializers.MeSessionType.Raw, TrueForge.MeSessionType> =
    core.serialization.enum_(["default", "oidc-connected"]);

export declare namespace MeSessionType {
    export type Raw = "default" | "oidc-connected";
}
