// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MetricsUnit: core.serialization.Schema<serializers.MetricsUnit.Raw, TrueForge.MetricsUnit> =
    core.serialization.enum_(["count", "$", "ms"]);

export declare namespace MetricsUnit {
    export type Raw = "count" | "$" | "ms";
}
