// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ResponseFormatJsonSchemaJsonSchema: core.serialization.ObjectSchema<
    serializers.ResponseFormatJsonSchemaJsonSchema.Raw,
    TrueForge.ResponseFormatJsonSchemaJsonSchema
> = core.serialization
    .object({
        description: core.serialization.string().optional(),
        name: core.serialization.string(),
        schema: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        strict: core.serialization.boolean().optionalNullable(),
    })
    .passthrough();

export declare namespace ResponseFormatJsonSchemaJsonSchema {
    export interface Raw {
        description?: string | null;
        name: string;
        schema?: Record<string, unknown> | null;
        strict?: (boolean | null | undefined) | null;
        [key: string]: any;
    }
}
