// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SandboxCreatedEvent: core.serialization.ObjectSchema<
    serializers.SandboxCreatedEvent.Raw,
    TrueForge.SandboxCreatedEvent
> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    id: core.serialization.string(),
    sandboxId: core.serialization.property("sandbox_id", core.serialization.string()),
    threadId: core.serialization.property("thread_id", core.serialization.string().nullable()),
    type: core.serialization.stringLiteral("sandbox.created"),
});

export declare namespace SandboxCreatedEvent {
    export interface Raw {
        created_at: string;
        id: string;
        sandbox_id: string;
        thread_id?: string | null;
        type: "sandbox.created";
    }
}
