// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SandboxConfig: core.serialization.ObjectSchema<serializers.SandboxConfig.Raw, TrueForge.SandboxConfig> =
    core.serialization.object({
        enabled: core.serialization.boolean(),
        environmentName: core.serialization.property("environment_name", core.serialization.string().optional()),
        fileDownloads: core.serialization.property("file_downloads", core.serialization.boolean().optional()),
    });

export declare namespace SandboxConfig {
    export interface Raw {
        enabled: boolean;
        environment_name?: string | null;
        file_downloads?: boolean | null;
    }
}
