// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SandboxEnvironmentSecret: core.serialization.ObjectSchema<
    serializers.SandboxEnvironmentSecret.Raw,
    TrueForge.SandboxEnvironmentSecret
> = core.serialization.object({
    env: core.serialization.string(),
    hosts: core.serialization.list(core.serialization.string()),
    value: core.serialization.string(),
});

export declare namespace SandboxEnvironmentSecret {
    export interface Raw {
        env: string;
        hosts: string[];
        value: string;
    }
}
