// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SessionMetricsMeterName: core.serialization.Schema<
    serializers.SessionMetricsMeterName.Raw,
    TrueForge.SessionMetricsMeterName
> = core.serialization.enum_([
    "total_sessions",
    "total_cost_in_usd",
    "total_turns",
    "cost_per_session_in_usd",
    "avg_turns_per_session",
    "min_turns_per_session",
    "max_turns_per_session",
    "median_turns_per_session",
    "min_session_duration_ms",
    "max_session_duration_ms",
    "median_session_duration_ms",
    "p95_session_duration_ms",
]);

export declare namespace SessionMetricsMeterName {
    export type Raw =
        | "total_sessions"
        | "total_cost_in_usd"
        | "total_turns"
        | "cost_per_session_in_usd"
        | "avg_turns_per_session"
        | "min_turns_per_session"
        | "max_turns_per_session"
        | "median_turns_per_session"
        | "min_session_duration_ms"
        | "max_session_duration_ms"
        | "median_session_duration_ms"
        | "p95_session_duration_ms";
}
