// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentSpec } from "./AgentSpec.js";

export const SessionAgentSpecBody: core.serialization.ObjectSchema<
    serializers.SessionAgentSpecBody.Raw,
    TrueForge.SessionAgentSpecBody
> = core.serialization.object({
    spec: AgentSpec,
});

export declare namespace SessionAgentSpecBody {
    export interface Raw {
        spec: AgentSpec.Raw;
    }
}
