// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SessionSourceSchedule: core.serialization.ObjectSchema<
    serializers.SessionSourceSchedule.Raw,
    TrueForge.SessionSourceSchedule
> = core.serialization.object({
    id: core.serialization.string(),
    runId: core.serialization.property("run_id", core.serialization.string()),
    type: core.serialization.stringLiteral("schedule"),
});

export declare namespace SessionSourceSchedule {
    export interface Raw {
        id: string;
        run_id: string;
        type: "schedule";
    }
}
