// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpAuthRequiredEvent } from "./McpAuthRequiredEvent.js";
import { McpInitializeEvent } from "./McpInitializeEvent.js";
import { ModelMessageEvent } from "./ModelMessageEvent.js";
import { SandboxCreatedEvent } from "./SandboxCreatedEvent.js";
import { ThreadCreatedEvent } from "./ThreadCreatedEvent.js";
import { ThreadDoneEvent } from "./ThreadDoneEvent.js";
import { ToolApprovalRequiredEvent } from "./ToolApprovalRequiredEvent.js";
import { ToolResponseEvent } from "./ToolResponseEvent.js";
import { ToolResponseRequiredEvent } from "./ToolResponseRequiredEvent.js";
import { TurnCreatedEvent } from "./TurnCreatedEvent.js";
import { TurnDoneEvent } from "./TurnDoneEvent.js";

export const SessionEvent: core.serialization.Schema<serializers.SessionEvent.Raw, TrueForge.SessionEvent> =
    core.serialization.undiscriminatedUnion([
        McpAuthRequiredEvent,
        McpInitializeEvent,
        ModelMessageEvent,
        SandboxCreatedEvent,
        ThreadCreatedEvent,
        ThreadDoneEvent,
        ToolApprovalRequiredEvent,
        ToolResponseEvent,
        ToolResponseRequiredEvent,
        TurnCreatedEvent,
        TurnDoneEvent,
    ]);

export declare namespace SessionEvent {
    export type Raw =
        | McpAuthRequiredEvent.Raw
        | McpInitializeEvent.Raw
        | ModelMessageEvent.Raw
        | SandboxCreatedEvent.Raw
        | ThreadCreatedEvent.Raw
        | ThreadDoneEvent.Raw
        | ToolApprovalRequiredEvent.Raw
        | ToolResponseEvent.Raw
        | ToolResponseRequiredEvent.Raw
        | TurnCreatedEvent.Raw
        | TurnDoneEvent.Raw;
}
