// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ResourceName } from "./ResourceName.js";

export const SkillVersion: core.serialization.ObjectSchema<serializers.SkillVersion.Raw, TrueForge.SkillVersion> =
    core.serialization.object({
        description: core.serialization.string(),
        fqn: core.serialization.string(),
        name: ResourceName,
        version: core.serialization.number(),
    });

export declare namespace SkillVersion {
    export interface Raw {
        description: string;
        fqn: string;
        name: ResourceName.Raw;
        version: number;
    }
}
