// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Skill: core.serialization.ObjectSchema<serializers.Skill.Raw, TrueForge.Skill> = core.serialization.object(
    {
        name: core.serialization.string(),
    },
);

export declare namespace Skill {
    export interface Raw {
        name: string;
    }
}
