// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TokenPagination: core.serialization.ObjectSchema<
    serializers.TokenPagination.Raw,
    TrueForge.TokenPagination
> = core.serialization.object({
    limit: core.serialization.number(),
    nextPageToken: core.serialization.property("next_page_token", core.serialization.string().optional()),
    previousPageToken: core.serialization.property("previous_page_token", core.serialization.string().optional()),
});

export declare namespace TokenPagination {
    export interface Raw {
        limit: number;
        next_page_token?: string | null;
        previous_page_token?: string | null;
    }
}
