// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ToolApprovalPolicyAllowSession } from "./ToolApprovalPolicyAllowSession.js";

export const ToolApprovalPolicyItem: core.serialization.ObjectSchema<
    serializers.ToolApprovalPolicyItem.Raw,
    TrueForge.ToolApprovalPolicyItem
> = core.serialization.object({
    action: ToolApprovalPolicyAllowSession,
    name: core.serialization.string(),
    serverName: core.serialization.property("server_name", core.serialization.string()),
});

export declare namespace ToolApprovalPolicyItem {
    export interface Raw {
        action: ToolApprovalPolicyAllowSession.Raw;
        name: string;
        server_name: string;
    }
}
