// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TrueFoundryRegistrySkill: core.serialization.ObjectSchema<
    serializers.TrueFoundryRegistrySkill.Raw,
    TrueForge.TrueFoundryRegistrySkill
> = core.serialization.object({
    description: core.serialization.string(),
    displayName: core.serialization.property("display_name", core.serialization.string()),
    name: core.serialization.string(),
    repositoryName: core.serialization.property("repository_name", core.serialization.string()),
    type: core.serialization.stringLiteral("truefoundry"),
    version: core.serialization.number(),
});

export declare namespace TrueFoundryRegistrySkill {
    export interface Raw {
        description: string;
        display_name: string;
        name: string;
        repository_name: string;
        type: "truefoundry";
        version: number;
    }
}
