// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TurnStatePaused: core.serialization.ObjectSchema<
    serializers.TurnStatePaused.Raw,
    TrueForge.TurnStatePaused
> = core.serialization.object({
    status: core.serialization.stringLiteral("paused"),
});

export declare namespace TurnStatePaused {
    export interface Raw {
        status: "paused";
    }
}
