// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnStatePaused } from "./TurnStatePaused.js";
import { TurnStateRunning } from "./TurnStateRunning.js";

export const TurnUpdateEventState: core.serialization.Schema<
    serializers.TurnUpdateEventState.Raw,
    TrueForge.TurnUpdateEventState
> = core.serialization.undiscriminatedUnion([TurnStatePaused, TurnStateRunning]);

export declare namespace TurnUpdateEventState {
    export type Raw = TurnStatePaused.Raw | TurnStateRunning.Raw;
}
