// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserToolApprovalMessage } from "./UserToolApprovalMessage.js";
import { UserToolApprovalPolicyMessage } from "./UserToolApprovalPolicyMessage.js";
import { UserToolResponseMessage } from "./UserToolResponseMessage.js";

export const TurnInboundEventItem: core.serialization.Schema<
    serializers.TurnInboundEventItem.Raw,
    TrueForge.TurnInboundEventItem
> = core.serialization.undiscriminatedUnion([
    UserToolApprovalMessage,
    UserToolApprovalPolicyMessage,
    UserToolResponseMessage,
]);

export declare namespace TurnInboundEventItem {
    export type Raw = UserToolApprovalMessage.Raw | UserToolApprovalPolicyMessage.Raw | UserToolResponseMessage.Raw;
}
