// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserToolApprovalInputEvent } from "./UserToolApprovalInputEvent.js";
import { UserToolApprovalPolicyMessage } from "./UserToolApprovalPolicyMessage.js";
import { UserToolResponseInputEvent } from "./UserToolResponseInputEvent.js";

export const TurnInboundEventItem: core.serialization.Schema<
    serializers.TurnInboundEventItem.Raw,
    TrueForge.TurnInboundEventItem
> = core.serialization.undiscriminatedUnion([
    UserToolApprovalInputEvent,
    UserToolApprovalPolicyMessage,
    UserToolResponseInputEvent,
]);

export declare namespace TurnInboundEventItem {
    export type Raw =
        | UserToolApprovalInputEvent.Raw
        | UserToolApprovalPolicyMessage.Raw
        | UserToolResponseInputEvent.Raw;
}
