// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UserMcpAuthContinueEvent: core.serialization.ObjectSchema<
    serializers.UserMcpAuthContinueEvent.Raw,
    TrueForge.UserMcpAuthContinueEvent
> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    id: core.serialization.string(),
    type: core.serialization.stringLiteral("user.mcp_auth_continue"),
});

export declare namespace UserMcpAuthContinueEvent {
    export interface Raw {
        created_at: string;
        id: string;
        type: "user.mcp_auth_continue";
    }
}
