// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebSearchConfig: core.serialization.ObjectSchema<
    serializers.WebSearchConfig.Raw,
    TrueForge.WebSearchConfig
> = core.serialization.object({
    enabled: core.serialization.boolean().optional(),
});

export declare namespace WebSearchConfig {
    export interface Raw {
        enabled?: boolean | null;
    }
}
