// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AgentName } from "../../../../types/AgentName.js";
import { AgentSpec } from "../../../../types/AgentSpec.js";

export const CreateAgentRequest: core.serialization.Schema<
    serializers.CreateAgentRequest.Raw,
    TrueForge.CreateAgentRequest
> = core.serialization.object({
    manifest: AgentSpec,
    name: AgentName,
});

export declare namespace CreateAgentRequest {
    export interface Raw {
        manifest: AgentSpec.Raw;
        name: AgentName.Raw;
    }
}
