// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../index.js";

/**
 * @example
 *     {
 *         description: "description",
 *         manifest: {
 *             model: {
 *                 name: "name"
 *             }
 *         },
 *         name: "name"
 *     }
 */
export interface CreateAgentRequest {
    description: string;
    manifest: TrueForge.AgentSpec;
    name: TrueForge.ResourceName;
}
