// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../src/api/index";
import { TrueForge } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    instructions: "instructions",
                    mcp_servers: [{ name: "name" }],
                    messages: [{ content: "content", type: "user.message" }],
                    model: { name: "name" },
                    response_format: { type: "json_object" },
                    skills: [{ name: "name" }],
                    id: "id",
                    name: "name",
                },
            ],
        };

        server.mockEndpoint().get("/api/v1/agents").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.list();
        expect(response).toEqual({
            data: [
                {
                    instructions: "instructions",
                    mcpServers: [
                        {
                            name: "name",
                        },
                    ],
                    messages: [
                        {
                            content: "content",
                            type: "user.message",
                        },
                    ],
                    model: {
                        name: "name",
                    },
                    responseFormat: {
                        type: "json_object",
                    },
                    skills: [
                        {
                            name: "name",
                        },
                    ],
                    id: "id",
                    name: "name",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server.mockEndpoint().get("/api/v1/agents").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.list();
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { model: { name: "name" }, name: "name" };
        const rawResponseBody = {
            data: {
                config: { iteration_limit: 1, sandbox: { enabled: true } },
                instructions: "instructions",
                mcp_servers: [{ name: "name" }],
                messages: [{ content: "content", type: "user.message" }],
                model: { name: "name" },
                response_format: { type: "json_object" },
                skills: [{ name: "name" }],
                id: "id",
                name: "name",
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.create({
            model: {
                name: "name",
            },
            name: "name",
        });
        expect(response).toEqual({
            data: {
                config: {
                    iterationLimit: 1,
                    sandbox: {
                        enabled: true,
                    },
                },
                instructions: "instructions",
                mcpServers: [
                    {
                        name: "name",
                    },
                ],
                messages: [
                    {
                        content: "content",
                        type: "user.message",
                    },
                ],
                model: {
                    name: "name",
                },
                responseFormat: {
                    type: "json_object",
                },
                skills: [
                    {
                        name: "name",
                    },
                ],
                id: "id",
                name: "name",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { name: "xy", model: { name: "x" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "xy",
                model: {
                    name: "x",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { name: "xy", model: { name: "x" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "xy",
                model: {
                    name: "x",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.ConflictError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { name: "xy", model: { name: "x" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "xy",
                model: {
                    name: "x",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                config: { iteration_limit: 1, sandbox: { enabled: true } },
                instructions: "instructions",
                mcp_servers: [{ name: "name" }],
                messages: [{ content: "content", type: "user.message" }],
                model: { name: "name" },
                response_format: { type: "json_object" },
                skills: [{ name: "name" }],
                id: "id",
                name: "name",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/agents/agent_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.get("agent_id");
        expect(response).toEqual({
            data: {
                config: {
                    iterationLimit: 1,
                    sandbox: {
                        enabled: true,
                    },
                },
                instructions: "instructions",
                mcpServers: [
                    {
                        name: "name",
                    },
                ],
                messages: [
                    {
                        content: "content",
                        type: "user.message",
                    },
                ],
                model: {
                    name: "name",
                },
                responseFormat: {
                    type: "json_object",
                },
                skills: [
                    {
                        name: "name",
                    },
                ],
                id: "id",
                name: "name",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/agents/agent_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.get("agent_id");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        server.mockEndpoint().delete("/api/v1/agents/agent_id").respondWith().statusCode(200).build();

        const response = await client.agents.delete("agent_id");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/agents/agent_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.delete("agent_id");
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { model: { name: "name" } };
        const rawResponseBody = {
            data: {
                config: { iteration_limit: 1, sandbox: { enabled: true } },
                instructions: "instructions",
                mcp_servers: [{ name: "name" }],
                messages: [{ content: "content", type: "user.message" }],
                model: { name: "name" },
                response_format: { type: "json_object" },
                skills: [{ name: "name" }],
                id: "id",
                name: "name",
            },
        };

        server
            .mockEndpoint()
            .put("/api/v1/agents/name")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.update("name", {
            model: {
                name: "name",
            },
        });
        expect(response).toEqual({
            data: {
                config: {
                    iterationLimit: 1,
                    sandbox: {
                        enabled: true,
                    },
                },
                instructions: "instructions",
                mcpServers: [
                    {
                        name: "name",
                    },
                ],
                messages: [
                    {
                        content: "content",
                        type: "user.message",
                    },
                ],
                model: {
                    name: "name",
                },
                responseFormat: {
                    type: "json_object",
                },
                skills: [
                    {
                        name: "name",
                    },
                ],
                id: "id",
                name: "name",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { model: { name: "x" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/agents/name")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update("name", {
                model: {
                    name: "x",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { model: { name: "x" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/agents/name")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update("name", {
                model: {
                    name: "x",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { model: { name: "x" } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/agents/name")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update("name", {
                model: {
                    name: "x",
                },
            });
        }).rejects.toThrow(TrueForgeTypes.UnprocessableEntityError);
    });
});
