// This file was auto-generated by Fern from our API Definition.

import * as TrueHarnessTypes from "../../src/api/index";
import { TrueHarness } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("McpServersClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: [{ auth: { type: "dcr" }, auth_status: "authenticated", name: "name", url: "url" }],
        };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.list();
        expect(response).toEqual({
            data: [
                {
                    auth: {
                        type: "dcr",
                    },
                    authStatus: "authenticated",
                    name: "name",
                    url: "url",
                },
            ],
        });
    });

    test("authorize (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { auth_url: "auth_url", status: "authenticated" };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers/name/authorize")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.authorize("name", {
            redirectUrl: "redirect_url",
        });
        expect(response).toEqual({
            authUrl: "auth_url",
            status: "authenticated",
        });
    });

    test("authorize (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers/name/authorize")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.mcpServers.authorize("name", {
                redirectUrl: "redirect_url",
            });
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("list_tools (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { data: [{ key: "value" }] };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers/name/tools")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.listTools("name");
        expect(response).toEqual({
            data: [
                {
                    key: "value",
                },
            ],
        });
    });

    test("list_tools (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers/name/tools")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.mcpServers.listTools("name");
        }).rejects.toThrow(TrueHarnessTypes.UnauthorizedError);
    });

    test("list_tools (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers/name/tools")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.mcpServers.listTools("name");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("list_tools (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers/name/tools")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.mcpServers.listTools("name");
        }).rejects.toThrow(TrueHarnessTypes.BadGatewayError);
    });
});
