// This file was auto-generated by Fern from our API Definition.

import { TrueHarness } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ModelsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: [{ name: "name", reasoning_efforts: ["reasoning_efforts"], max_output_tokens: 1 }],
        };

        server.mockEndpoint().get("/v1/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.models.list();
        expect(response).toEqual({
            data: [
                {
                    name: "name",
                    reasoningEfforts: ["reasoning_efforts"],
                    maxOutputTokens: 1,
                },
            ],
        });
    });
});
