// This file was auto-generated by Fern from our API Definition.

import * as TrueHarnessTypes from "../../src/api/index";
import { TrueHarness } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SessionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    agent_spec: { model: { name: "name" } },
                    title: "title",
                    created_at: "created_at",
                    updated_at: "updated_at",
                },
            ],
            pagination: { next_page_token: "next_page_token", previous_page_token: "previous_page_token", limit: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/sessions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    id: "id",
                    agentSpec: {
                        model: {
                            name: "name",
                        },
                    },
                    title: "title",
                    createdAt: "created_at",
                    updatedAt: "updated_at",
                },
            ],
            pagination: {
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
                limit: 1,
            },
        };
        const page = await client.sessions.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server.mockEndpoint().get("/v1/sessions").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.sessions.list();
        }).rejects.toThrow(TrueHarnessTypes.BadRequestError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "name" } } };
        const rawResponseBody = {
            data: {
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ type: "user.message", content: "content" }],
                    mcp_servers: [{ name: "name" }],
                    response_format: { type: "text" },
                    skills: [{ type: "git", url: "url", name: "name", description: "description", ref: "ref" }],
                    variables: { key: "value" },
                },
                title: "title",
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.create({
            agentSpec: {
                model: {
                    name: "name",
                },
            },
        });
        expect(response).toEqual({
            data: {
                id: "id",
                agentSpec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            type: "user.message",
                            content: "content",
                        },
                    ],
                    mcpServers: [
                        {
                            name: "name",
                        },
                    ],
                    responseFormat: {
                        type: "text",
                    },
                    skills: [
                        {
                            type: "git",
                            url: "url",
                            name: "name",
                            description: "description",
                            ref: "ref",
                        },
                    ],
                    variables: {
                        key: "value",
                    },
                },
                title: "title",
                createdAt: "created_at",
                updatedAt: "updated_at",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.create({
                agentSpec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueHarnessTypes.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.create({
                agentSpec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueHarnessTypes.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ type: "user.message", content: "content" }],
                    mcp_servers: [{ name: "name" }],
                    response_format: { type: "text" },
                    skills: [{ type: "git", url: "url", name: "name", description: "description", ref: "ref" }],
                    variables: { key: "value" },
                },
                title: "title",
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.get("sessionId");
        expect(response).toEqual({
            data: {
                id: "id",
                agentSpec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            type: "user.message",
                            content: "content",
                        },
                    ],
                    mcpServers: [
                        {
                            name: "name",
                        },
                    ],
                    responseFormat: {
                        type: "text",
                    },
                    skills: [
                        {
                            type: "git",
                            url: "url",
                            name: "name",
                            description: "description",
                            ref: "ref",
                        },
                    ],
                    variables: {
                        key: "value",
                    },
                },
                title: "title",
                createdAt: "created_at",
                updatedAt: "updated_at",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.get("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ type: "user.message", content: "content" }],
                    mcp_servers: [{ name: "name" }],
                    response_format: { type: "text" },
                    skills: [{ type: "git", url: "url", name: "name", description: "description", ref: "ref" }],
                    variables: { key: "value" },
                },
                title: "title",
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/sessions/sessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.update("sessionId");
        expect(response).toEqual({
            data: {
                id: "id",
                agentSpec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            type: "user.message",
                            content: "content",
                        },
                    ],
                    mcpServers: [
                        {
                            name: "name",
                        },
                    ],
                    responseFormat: {
                        type: "text",
                    },
                    skills: [
                        {
                            type: "git",
                            url: "url",
                            name: "name",
                            description: "description",
                            ref: "ref",
                        },
                    ],
                    variables: {
                        key: "value",
                    },
                },
                title: "title",
                createdAt: "created_at",
                updatedAt: "updated_at",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/sessions/sessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.update("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/sessions/sessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.update("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/sessions/sessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.update("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.UnprocessableEntityError);
    });

    test("cancel (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/sessions/sessionId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.cancel("sessionId");
        expect(response).toEqual({});
    });

    test("cancel (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/sessions/sessionId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.cancel("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("cancel (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/sessions/sessionId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(412)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.cancel("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.PreconditionFailedError);
    });

    test("list_events (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    turn_id: "turn_id",
                    event: {
                        type: "turn.created",
                        id: "id",
                        turn_id: "turn_id",
                        previous_turn_id: null,
                        state: { status: "running" },
                        created_at: "created_at",
                        thread_id: null,
                    },
                },
            ],
            pagination: { next_page_token: "next_page_token", previous_page_token: "previous_page_token", limit: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/sessions/sessionId/events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    turnId: "turn_id",
                    event: {
                        type: "turn.created",
                        id: "id",
                        turnId: "turn_id",
                        previousTurnId: null,
                        state: {
                            status: "running",
                        },
                        createdAt: "created_at",
                        threadId: null,
                    },
                },
            ],
            pagination: {
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
                limit: 1,
            },
        };
        const page = await client.sessions.listEvents("sessionId");

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list_events (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId/events")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.listEvents("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.BadRequestError);
    });

    test("list_events (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId/events")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.listEvents("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("list_turns (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    session_id: "session_id",
                    previous_turn_id: "previous_turn_id",
                    input: [{ type: "user.message", content: "content" }],
                    state: { status: "running" },
                    created_at: "created_at",
                },
            ],
            pagination: { next_page_token: "next_page_token", previous_page_token: "previous_page_token", limit: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/sessions/sessionId/turns")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    id: "id",
                    sessionId: "session_id",
                    previousTurnId: "previous_turn_id",
                    input: [
                        {
                            type: "user.message",
                            content: "content",
                        },
                    ],
                    state: {
                        status: "running",
                    },
                    createdAt: "created_at",
                },
            ],
            pagination: {
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
                limit: 1,
            },
        };
        const page = await client.sessions.listTurns("sessionId");

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list_turns (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId/turns")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.listTurns("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.BadRequestError);
    });

    test("list_turns (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId/turns")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.listTurns("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("create_turn (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody =
            'event: \ndata: {"content":"content","name":"name","refusal":"refusal","reasoning_content":"reasoning_content","tool_calls":[{"id":"id","type":"function","function":{"name":"name","arguments":"arguments"},"provider_specific_fields":{"key":"value"},"tool_info":{"type":"truefoundry-system","name":"name"}}],"type":"model.message","id":"id","thread_id":"thread_id","finish_reason":"stop","created_at":"created_at","usage":{"input_tokens":1,"output_tokens":1,"cache_read_tokens":1,"cache_write_tokens":1,"input_tokens_breakdown":{"harness":1,"skills":1,"instructions":1,"tool_definitions":1,"messages":1}}}\n\n';

        server
            .mockEndpoint()
            .post("/v1/sessions/sessionId/turns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.sessions.createTurn("sessionId");
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                content: "content",
                name: "name",
                refusal: "refusal",
                reasoningContent: "reasoning_content",
                toolCalls: [
                    {
                        id: "id",
                        type: "function",
                        function: {
                            name: "name",
                            arguments: "arguments",
                        },
                        providerSpecificFields: {
                            key: "value",
                        },
                        toolInfo: {
                            type: "truefoundry-system",
                            name: "name",
                        },
                    },
                ],
                type: "model.message",
                id: "id",
                threadId: "thread_id",
                finishReason: "stop",
                createdAt: "created_at",
                usage: {
                    inputTokens: 1,
                    outputTokens: 1,
                    cacheReadTokens: 1,
                    cacheWriteTokens: 1,
                    inputTokensBreakdown: {
                        harness: 1,
                        skills: 1,
                        instructions: 1,
                        toolDefinitions: 1,
                        messages: 1,
                    },
                },
            },
        ]);
    });

    test("create_turn (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/sessions/sessionId/turns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createTurn("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.BadRequestError);
    });

    test("create_turn (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/sessions/sessionId/turns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createTurn("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("create_turn (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/sessions/sessionId/turns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(412)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createTurn("sessionId");
        }).rejects.toThrow(TrueHarnessTypes.PreconditionFailedError);
    });

    test("get_turn (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                session_id: "session_id",
                previous_turn_id: "previous_turn_id",
                input: [{ type: "user.message", content: "content" }],
                state: { status: "running" },
                created_at: "created_at",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId/turns/turnId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.getTurn("sessionId", "turnId");
        expect(response).toEqual({
            data: {
                id: "id",
                sessionId: "session_id",
                previousTurnId: "previous_turn_id",
                input: [
                    {
                        type: "user.message",
                        content: "content",
                    },
                ],
                state: {
                    status: "running",
                },
                createdAt: "created_at",
            },
        });
    });

    test("get_turn (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId/turns/turnId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.getTurn("sessionId", "turnId");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });

    test("list_turn_events (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    type: "turn.created",
                    id: "id",
                    turn_id: "turn_id",
                    previous_turn_id: "previous_turn_id",
                    input: [{ type: "user.message", content: "content" }],
                    state: { status: "running" },
                    created_at: "created_at",
                    thread_id: "thread_id",
                },
            ],
            pagination: { next_page_token: "next_page_token", previous_page_token: "previous_page_token", limit: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/sessions/sessionId/turns/turnId/events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    type: "turn.created",
                    id: "id",
                    turnId: "turn_id",
                    previousTurnId: "previous_turn_id",
                    input: [
                        {
                            type: "user.message",
                            content: "content",
                        },
                    ],
                    state: {
                        status: "running",
                    },
                    createdAt: "created_at",
                    threadId: "thread_id",
                },
            ],
            pagination: {
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
                limit: 1,
            },
        };
        const page = await client.sessions.listTurnEvents("sessionId", "turnId");

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list_turn_events (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId/turns/turnId/events")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.listTurnEvents("sessionId", "turnId");
        }).rejects.toThrow(TrueHarnessTypes.BadRequestError);
    });

    test("list_turn_events (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueHarness({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/sessions/sessionId/turns/turnId/events")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.listTurnEvents("sessionId", "turnId");
        }).rejects.toThrow(TrueHarnessTypes.NotFoundError);
    });
});
