// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export type ActionRequiredEvent =
    | TrueForge.McpAuthRequiredEvent
    | TrueForge.ToolApprovalRequiredEvent
    | TrueForge.ToolResponseRequiredEvent;
