// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../index.js";

/**
 * Agent Definition
 */
export interface AgentWriteRequest extends TrueHarness.AgentSpec {
    name: TrueHarness.ResourceName;
}
