// This file was auto-generated by Fern from our API Definition.

export const CallerSuppliedModelProviderType = {
    Alibaba: "alibaba",
    Custom: "custom",
} as const;
export type CallerSuppliedModelProviderType =
    (typeof CallerSuppliedModelProviderType)[keyof typeof CallerSuppliedModelProviderType];
