// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../index.js";

export interface CatalogProvider {
    models: TrueHarness.ModelEntry[];
    name: TrueHarness.ResourceName;
    type: TrueHarness.CatalogProviderType;
}
