// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface CatalogWellKnownModelProvider {
    /** URL of the provider logo asset. */
    logo?: string;
    /** Preset models; empty on the `custom` sentinel. */
    models: TrueForge.ModelEntry[];
    /** Well-known provider type (catalog excludes `custom`). */
    type: TrueForge.CatalogWellKnownModelProviderType;
}
