// This file was auto-generated by Fern from our API Definition.

export const CatalogProviderType = {
    Openai: "openai",
    Anthropic: "anthropic",
} as const;
export type CatalogProviderType = (typeof CatalogProviderType)[keyof typeof CatalogProviderType];
