// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface GoogleGeminiModelProvider {
    auth: TrueForge.ModelProviderAuth;
    /** Override of the provider's default API base URL. */
    baseUrl?: string;
    models: TrueForge.ModelEntry[];
    name?: "google-gemini";
    type: "google-gemini";
}
