// This file was auto-generated by Fern from our API Definition.

export interface LargeToolResponseConfig {
    /** Offload oversized tool responses to a sandbox file. Default: true. */
    enabled?: boolean;
}
