// This file was auto-generated by Fern from our API Definition.

export interface ListMcpServerToolsResponse {
    /** MCP `tools/list` entries, passed through verbatim from the MCP server. */
    data: Record<string, unknown>[];
}
