// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface McpAuthRequiredEvent extends TrueForge.BaseMcpAuthRequiredEvent {
    mcpServers: TrueForge.McpServerAuthInfo[];
    type: "mcp.auth_required";
}
