// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../index.js";

export interface McpAuthStatus {
    /** When auth is required, this contains the URL to redirect the user to for authorization. */
    authorizationUrl?: string;
    status: TrueHarness.McpAuthStatusStatus;
}
