// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface McpInitializeEvent {
    /** ISO 8601 event timestamp. */
    createdAt: string;
    /** Unique identifier for the event (monotonic ULID). */
    id: string;
    /** Servers that were initialized. */
    mcpServers: TrueForge.McpServerInitInfo[];
    /** Thread that triggered initialization. */
    threadId: string;
    type: "mcp.initialize";
}
