// This file was auto-generated by Fern from our API Definition.

export interface McpServerAuthInfo {
    /** URL the user must visit to complete OAuth for this server. */
    authUrl: string;
    /** Internal MCP server id. */
    id: string;
    /** Configured MCP server name. */
    name: string;
}
