// This file was auto-generated by Fern from our API Definition.

/** Session kind: `default` when no OIDC id_token cookie is present; `passport` after a successful login. */
export const MeResponseType = {
    Default: "default",
    Passport: "passport",
} as const;
export type MeResponseType = (typeof MeResponseType)[keyof typeof MeResponseType];
