// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ModelMessageEvent {
    content?: TrueForge.ModelMessageEventContent | null;
    createdAt: string;
    finishReason?: TrueForge.FinishReason | null;
    /** Unique identifier for the event */
    id: string;
    name?: string;
    reasoningContent?: string;
    refusal?: string | null;
    threadId: string;
    toolCalls?: TrueForge.ToolCall[];
    type: "model.message";
    usage?: TrueForge.ModelMessageUsage;
}
