// This file was auto-generated by Fern from our API Definition.

export interface ModelParams {
    maxTokens?: number;
    parallelToolCalls?: boolean;
    reasoningEffort?: string;
    temperature?: number;
    topK?: number;
    topP?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
