// This file was auto-generated by Fern from our API Definition.

export interface ModelEntryZero {
    apiKey?: string;
    baseUrl?: string;
    headers?: Record<string, string>;
    maxOutputTokens: number;
    modelId?: string;
    name: string;
    provider: "openai";
    reasoningEfforts?: string[];
}
