// This file was auto-generated by Fern from our API Definition.

export const ModelEntryOneProvider = {
    Anthropic: "anthropic",
    Google: "google",
    Mistral: "mistral",
    Openrouter: "openrouter",
    Portkey: "portkey",
    Kimi: "kimi",
} as const;
export type ModelEntryOneProvider = (typeof ModelEntryOneProvider)[keyof typeof ModelEntryOneProvider];
