// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ModelMessageUsage {
    cacheReadTokens?: number;
    cacheWriteTokens?: number;
    inputTokens: number;
    inputTokensBreakdown: TrueForge.ModelMessageUsageInputTokensBreakdown;
    outputTokens: number;
}
