// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface RuntimeConfig {
    askUserQuestions?: TrueForge.AskUserQuestionsConfig;
    contextManagement?: TrueForge.ContextManagementConfig;
    dynamicSubAgents?: TrueForge.DynamicSubAgentsConfig;
    generativeUi?: TrueForge.GenerativeUiConfig;
    iterationLimit?: number;
    sandbox?: TrueForge.SandboxConfig;
}
