// This file was auto-generated by Fern from our API Definition.

/**
 * Provider-specific build metadata; null when the provider has none.
 */
export type SandboxBuildMetadata = Record<string, string | null> | null;
