// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface SessionAgentValue {
    def: TrueForge.AgentSpec;
    type: "value";
}
