// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../index.js";

export interface ThreadStateError {
    error: string;
    output?: TrueHarness.ModelMessageEvent;
    status: "error";
}
