// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ThreadDoneEvent extends TrueForge.BaseThreadDoneEvent {
    createdAt: string;
    /** Unique identifier for the event */
    id: string;
    state: TrueForge.ThreadState;
    type: "thread.done";
}
