// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../index.js";

export interface ThreadDoneEvent extends TrueHarness.BaseThreadDoneEvent {
    type: "thread.done";
    /** Unique identifier for the event */
    id: string;
    createdAt: string;
    state: TrueHarness.ThreadState;
}
