// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface TogetherAiModelProvider {
    auth: TrueForge.ModelProviderAuth;
    /** Override of the provider's default API base URL. */
    baseUrl?: string;
    models: TrueForge.ModelEntry[];
    name?: "together";
    type: "together";
}
