// This file was auto-generated by Fern from our API Definition.

export interface ToolResponseEvent {
    content: string;
    createdAt: string;
    /** Unique identifier for the event */
    id: string;
    threadId: string;
    toolCallId: string;
    type: "tool.response";
}
