// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../index.js";

export interface Turn {
    id: string;
    sessionId: string;
    previousTurnId: string | null;
    input?: TrueHarness.TurnInputItem[];
    state: TrueHarness.TurnState;
    createdAt: string;
}
