// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../index.js";

export interface TurnStateCancelled {
    completedAt: string;
    reason: TrueHarness.TurnStateCancelledReason;
    status: "cancelled";
}
