// This file was auto-generated by Fern from our API Definition.

export const WellKnownModelProviderType = {
    Openai: "openai",
    Anthropic: "anthropic",
    GoogleGemini: "google-gemini",
    Fireworks: "fireworks",
    Zai: "zai",
    Moonshot: "moonshot",
} as const;
export type WellKnownModelProviderType = (typeof WellKnownModelProviderType)[keyof typeof WellKnownModelProviderType];
