// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { McpServerManifestAuth } from "../../types/McpServerManifestAuth.js";

export const McpServerManifest: core.serialization.Schema<
    serializers.settings.McpServerManifest.Raw,
    TrueForge.settings.McpServerManifest
> = core.serialization.object({
    auth: McpServerManifestAuth.optional(),
    description: core.serialization.string(),
    name: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace McpServerManifest {
    export interface Raw {
        auth?: McpServerManifestAuth.Raw | null;
        description: string;
        name: string;
        url: string;
    }
}
