// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { SessionAgent } from "../../../../types/SessionAgent.js";

export const CreateSessionRequest: core.serialization.Schema<
    serializers.CreateSessionRequest.Raw,
    TrueForge.CreateSessionRequest
> = core.serialization.object({
    agent: SessionAgent,
});

export declare namespace CreateSessionRequest {
    export interface Raw {
        agent: SessionAgent.Raw;
    }
}
