// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const SubscribeTurnRequest: core.serialization.Schema<
    serializers.SubscribeTurnRequest.Raw,
    TrueHarness.SubscribeTurnRequest
> = core.serialization.object({
    afterSequenceNumber: core.serialization.property("after_sequence_number", core.serialization.number().optional()),
});

export declare namespace SubscribeTurnRequest {
    export interface Raw {
        after_sequence_number?: number | null;
    }
}
