// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetCodeSnippetsAgentsRequest {
    /** Public SDK base URL from the browser. When omitted, derived from the request origin and PUBLIC_BASE_URL. */
    baseUrl?: string;
}
