// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../../src/api/index";
import { TrueForge } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("McpServersClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    auth: { type: "dcr" },
                    auth_status: { status: "authenticated" },
                    name: "name",
                    type: "remote",
                    url: "url",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/settings/mcp-servers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.mcpServers.list();
        expect(response).toEqual({
            data: [
                {
                    auth: {
                        type: "dcr",
                    },
                    authStatus: {
                        status: "authenticated",
                    },
                    name: "name",
                    type: "remote",
                    url: "url",
                },
            ],
        });
    });

    test("upsert (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { name: "name", type: "remote", url: "url" };
        const rawResponseBody = {
            data: {
                auth: { type: "dcr" },
                auth_status: { authorization_url: "authorization_url", status: "authenticated" },
                name: "name",
                type: "remote",
                url: "url",
            },
        };

        server
            .mockEndpoint()
            .put("/api/v1/settings/mcp-servers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.mcpServers.upsert({
            name: "name",
            url: "url",
        });
        expect(response).toEqual({
            data: {
                auth: {
                    type: "dcr",
                },
                authStatus: {
                    authorizationUrl: "authorization_url",
                    status: "authenticated",
                },
                name: "name",
                type: "remote",
                url: "url",
            },
        });
    });

    test("upsert (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = { name: "xy", type: "remote", url: "url" };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/settings/mcp-servers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.mcpServers.upsert({
                name: "xy",
                url: "url",
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("catalog", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [{ auth: { type: "dcr" }, logo: "logo", name: "name", type: "remote", url: "url" }],
        };

        server
            .mockEndpoint()
            .get("/api/v1/settings/mcp-servers/catalog")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.mcpServers.catalog();
        expect(response).toEqual({
            data: [
                {
                    auth: {
                        type: "dcr",
                    },
                    logo: "logo",
                    name: "name",
                    type: "remote",
                    url: "url",
                },
            ],
        });
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                auth: { type: "dcr" },
                auth_status: { authorization_url: "authorization_url", status: "authenticated" },
                name: "name",
                type: "remote",
                url: "url",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/settings/mcp-servers/name")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.mcpServers.get("name");
        expect(response).toEqual({
            data: {
                auth: {
                    type: "dcr",
                },
                authStatus: {
                    authorizationUrl: "authorization_url",
                    status: "authenticated",
                },
                name: "name",
                type: "remote",
                url: "url",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/settings/mcp-servers/name")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.mcpServers.get("name");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("list_tools (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { data: [{ key: "value" }] };

        server
            .mockEndpoint()
            .get("/api/v1/settings/mcp-servers/name/tools")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.mcpServers.listTools("name");
        expect(response).toEqual({
            data: [
                {
                    key: "value",
                },
            ],
        });
    });

    test("list_tools (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/settings/mcp-servers/name/tools")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.mcpServers.listTools("name");
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("list_tools (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/settings/mcp-servers/name/tools")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.mcpServers.listTools("name");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("list_tools (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/settings/mcp-servers/name/tools")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.mcpServers.listTools("name");
        }).rejects.toThrow(TrueForgeTypes.BadGatewayError);
    });
});
