// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { ResourceName } from "../../../../types/ResourceName.js";
import { ScheduleManifest } from "../../../../types/ScheduleManifest.js";

export const CreateScheduleRequest: core.serialization.Schema<
    serializers.CreateScheduleRequest.Raw,
    TrueForge.CreateScheduleRequest
> = core.serialization.object({
    agentId: core.serialization.property("agent_id", core.serialization.string()),
    manifest: ScheduleManifest,
    name: ResourceName,
});

export declare namespace CreateScheduleRequest {
    export interface Raw {
        agent_id: string;
        manifest: ScheduleManifest.Raw;
        name: ResourceName.Raw;
    }
}
