// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../index.js";

/**
 * @example
 *     {
 *         manifest: {
 *             auth: {
 *                 apiKey: "api_key"
 *             },
 *             models: [{
 *                     modelId: "model_id",
 *                     name: "name",
 *                     properties: {}
 *                 }],
 *             type: "alibaba"
 *         }
 *     }
 */
export interface CreateModelProviderRequest {
    manifest: TrueForge.ModelProviderManifest;
}
