// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { ModelProviderManifest } from "../../../../../../types/ModelProviderManifest.js";

export const PutModelProviderRequest: core.serialization.Schema<
    serializers.settings.PutModelProviderRequest.Raw,
    TrueForge.settings.PutModelProviderRequest
> = core.serialization.object({
    manifest: ModelProviderManifest,
});

export declare namespace PutModelProviderRequest {
    export interface Raw {
        manifest: ModelProviderManifest.Raw;
    }
}
