// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../../../index.js";

/**
 * @example
 *     {
 *         auth: {
 *             apiKey: "api_key"
 *         },
 *         baseUrl: "base_url",
 *         models: [{
 *                 modelId: "model_id",
 *                 name: "name",
 *                 properties: {
 *                     contextLength: 1,
 *                     maxOutputTokens: 1
 *                 }
 *             }],
 *         name: "name",
 *         type: "openai"
 *     }
 */
export interface PutModelProviderRequest {
    auth: TrueHarness.ModelProviderAuth;
    /** Base URL of the provider's API. */
    baseUrl: string;
    models: TrueHarness.PutModelProviderRequestModelsItem[];
    name: TrueHarness.ResourceName;
    type: TrueHarness.ProviderType;
}
