// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../index.js";

/**
 * @example
 *     {
 *         description: "description",
 *         name: "name",
 *         url: "url"
 *     }
 */
export interface McpServerManifest {
    /** Optional auth settings. Omit when the server needs no credentials. */
    auth?: TrueForge.settings.McpServerManifestAuth;
    /** Concise summary of what this MCP server provides. */
    description: string;
    /** Fully qualified name. Unique within a tenant. */
    name: string;
    /** URL of the remote MCP server. */
    url: string;
}
