// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListTurnsSessionsRequest {
    /** Page size. Defaults to 10, max 100. */
    limit?: number;
    /** Opaque token from a previous response `next_page_token`. */
    pageToken?: string;
}
