// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListTurnEventsSessionsRequest {
    /** Max events per response. Default 25, max 100. */
    limit?: number;
    /** Opaque token from a previous response `next_page_token`. */
    pageToken?: string;
    /** Sort events by insertion order. Defaults to "asc". */
    order?: TrueHarness.ListTurnEventsOrder;
}
