// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { PreviousTurnIdInput } from "../../../../types/PreviousTurnIdInput.js";
import { UserMessage } from "../../../../types/UserMessage.js";

export const CreateTurnSessionsRequest: core.serialization.Schema<
    serializers.CreateTurnSessionsRequest.Raw,
    TrueForge.CreateTurnSessionsRequest
> = core.serialization.object({
    input: core.serialization.list(UserMessage).optional(),
    previousTurnId: core.serialization.property("previous_turn_id", PreviousTurnIdInput.optional()),
});

export declare namespace CreateTurnSessionsRequest {
    export interface Raw {
        input?: UserMessage.Raw[] | null;
        previous_turn_id?: PreviousTurnIdInput.Raw | null;
    }
}
