// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { SessionAgentSpecBody } from "../../../../types/SessionAgentSpecBody.js";
import { SessionMetadata } from "../../../../types/SessionMetadata.js";

export const UpdateSessionRequest: core.serialization.Schema<
    serializers.UpdateSessionRequest.Raw,
    TrueForge.UpdateSessionRequest
> = core.serialization.object({
    agent: SessionAgentSpecBody.optional(),
    metadata: SessionMetadata.optional(),
});

export declare namespace UpdateSessionRequest {
    export interface Raw {
        agent?: SessionAgentSpecBody.Raw | null;
        metadata?: SessionMetadata.Raw | null;
    }
}
