import type { SemanticTokens, ThemePreset } from '../types.js';

export type PresetTokens = {
  light: SemanticTokens;
  dark: SemanticTokens;
};

const trueforge: PresetTokens = {
  light: {
    background: '#ffffff',
    foreground: '#09090b',
    card: '#ffffff',
    cardForeground: '#09090b',
    popover: '#ffffff',
    popoverForeground: '#09090b',
    primary: '#09090b',
    primaryForeground: '#ffffff',
    secondary: '#f4f4f5',
    secondaryForeground: '#09090b',
    muted: '#f4f4f5',
    mutedForeground: '#62626a',
    accent: '#f1f1f2',
    accentForeground: '#09090b',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    success: '#16a34a',
    successForeground: '#ffffff',
    warning: '#d97706',
    warningForeground: '#ffffff',
    border: '#e4e4e7',
    input: '#e4e4e7',
    ring: '#09090b',
    radius: '0.5rem',
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    composerRadius: '1.5rem',
    userBubble: '#09090b',
    userBubbleForeground: '#ffffff',
  },
  dark: {
    background: '#1f1f22',
    foreground: '#fdfdfd',
    card: '#18181b',
    cardForeground: '#fdfdfd',
    popover: '#18181b',
    popoverForeground: '#fdfdfd',
    primary: '#6366f1',
    primaryForeground: '#ffffff',
    secondary: '#27272a',
    secondaryForeground: '#fdfdfd',
    muted: '#27272a',
    mutedForeground: '#a1a1aa',
    accent: '#343439',
    accentForeground: '#fdfdfd',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    success: '#4ade80',
    successForeground: '#052e16',
    warning: '#fbbf24',
    warningForeground: '#422006',
    border: '#343439',
    input: '#343439',
    ring: '#6366f1',
    radius: '0.5rem',
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    composerRadius: '1.5rem',
    userBubble: '#6366f1',
    userBubbleForeground: '#ffffff',
  },
};

/** assistant-ui's Claude clone: warm cream surfaces, serif type, and orange actions. */
const claude: PresetTokens = {
  light: {
    background: '#f0ece0',
    foreground: '#1a1a18',
    card: '#ffffff',
    cardForeground: '#1a1a18',
    popover: '#ffffff',
    popoverForeground: '#1a1a18',
    primary: '#c96442',
    primaryForeground: '#ffffff',
    secondary: '#e5e0d6',
    secondaryForeground: '#1a1a18',
    muted: '#e5e0d6',
    mutedForeground: '#5b5950',
    accent: '#1a1a180d',
    accentForeground: '#1a1a18',
    destructive: '#d03b3b',
    destructiveForeground: '#ffffff',
    success: '#15803d',
    successForeground: '#ffffff',
    warning: '#b45309',
    warningForeground: '#ffffff',
    border: '#e5e0d6',
    input: '#e5e0d6',
    ring: '#c96442',
    radius: '1rem',
    fontFamily: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
    composerRadius: '1rem',
    userBubble: '#e5e0d6',
    userBubbleForeground: '#1a1a18',
  },
  dark: {
    background: '#2b2a27',
    foreground: '#eeeeee',
    card: '#1f1e1b',
    cardForeground: '#eeeeee',
    popover: '#1f1e1b',
    popoverForeground: '#eeeeee',
    primary: '#c96442',
    primaryForeground: '#ffffff',
    secondary: '#3d3a35',
    secondaryForeground: '#eeeeee',
    muted: '#1f1e1b',
    mutedForeground: '#a3a098',
    accent: '#ffffff0d',
    accentForeground: '#eeeeee',
    destructive: '#d03b3b',
    destructiveForeground: '#ffffff',
    success: '#4ade80',
    successForeground: '#052e16',
    warning: '#fbbf24',
    warningForeground: '#422006',
    border: '#3d3a35',
    input: '#3d3a35',
    ring: '#c96442',
    radius: '1rem',
    fontFamily: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
    composerRadius: '1rem',
    userBubble: '#3d3a35',
    userBubbleForeground: '#eeeeee',
  },
};

/** assistant-ui's ChatGPT clone: stark surfaces and high-contrast controls. */
const chatgpt: PresetTokens = {
  light: {
    background: '#ffffff',
    foreground: '#0d0d0d',
    card: '#ffffff',
    cardForeground: '#0d0d0d',
    popover: '#ffffff',
    popoverForeground: '#0d0d0d',
    primary: '#0d0d0d',
    primaryForeground: '#ffffff',
    secondary: '#ececec',
    secondaryForeground: '#0d0d0d',
    muted: '#f9f9f9',
    mutedForeground: '#5d5d5d',
    accent: '#00000012',
    accentForeground: '#0d0d0d',
    destructive: '#ff002a',
    destructiveForeground: '#ffffff',
    success: '#16a34a',
    successForeground: '#ffffff',
    warning: '#d97706',
    warningForeground: '#ffffff',
    border: '#e5e5e5',
    input: '#e5e5e5',
    ring: '#0d0d0d',
    radius: '1.5rem',
    fontFamily: '"GeistSans", "GeistSans Fallback", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    composerRadius: '1.75rem',
    userBubble: '#e9e9e980',
    userBubbleForeground: '#0d0d0d',
  },
  dark: {
    background: '#000000',
    foreground: '#ececec',
    card: '#212121',
    cardForeground: '#ececec',
    popover: '#212121',
    popoverForeground: '#ececec',
    primary: '#ffffff',
    primaryForeground: '#0d0d0d',
    secondary: '#303030',
    secondaryForeground: '#ffffff',
    muted: '#303030',
    mutedForeground: '#cdcdcd',
    accent: '#ffffff26',
    accentForeground: '#ffffff',
    destructive: '#ff002a',
    destructiveForeground: '#ffffff',
    success: '#4ade80',
    successForeground: '#052e16',
    warning: '#fbbf24',
    warningForeground: '#422006',
    border: '#ffffff26',
    input: '#ffffff26',
    ring: '#ffffff',
    radius: '1.5rem',
    fontFamily: '"GeistSans", "GeistSans Fallback", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    composerRadius: '1.75rem',
    userBubble: '#323232',
    userBubbleForeground: '#ffffff',
  },
};

/** Gemini's Material surfaces and blue action accents. */
const gemini: PresetTokens = {
  light: {
    background: '#fdfcfc',
    foreground: '#1f1f1f',
    card: '#ffffff',
    cardForeground: '#1f1f1f',
    popover: '#f0f4f9',
    popoverForeground: '#1f1f1f',
    primary: '#1f3b9b',
    primaryForeground: '#ffffff',
    secondary: '#e8eaed',
    secondaryForeground: '#1f1f1f',
    muted: '#f8fafd',
    mutedForeground: '#444746',
    accent: '#e9eef6',
    accentForeground: '#1f1f1f',
    destructive: '#b3261e',
    destructiveForeground: '#ffffff',
    success: '#188038',
    successForeground: '#ffffff',
    warning: '#b06000',
    warningForeground: '#ffffff',
    border: '#dadce0',
    input: '#dadce0',
    ring: '#1f3b9b',
    radius: '1rem',
    fontFamily: '"GeistSans", "GeistSans Fallback", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    composerRadius: '2rem',
    userBubble: '#f3f6fc',
    userBubbleForeground: '#1f1f1f',
  },
  dark: {
    background: '#0c0c0c',
    foreground: '#e3e3e3',
    card: '#1e1f20',
    cardForeground: '#e3e3e3',
    popover: '#282a2c',
    popoverForeground: '#e3e3e3',
    primary: '#a8c7fa',
    primaryForeground: '#062e6f',
    secondary: '#2b2c2e',
    secondaryForeground: '#e3e3e3',
    muted: '#1b1b1b',
    mutedForeground: '#c4c7c5',
    accent: '#282a2c',
    accentForeground: '#e3e3e3',
    destructive: '#f2b8b5',
    destructiveForeground: '#601410',
    success: '#81c995',
    successForeground: '#0d3b1e',
    warning: '#fdd663',
    warningForeground: '#4a3000',
    border: '#3c4043',
    input: '#3c4043',
    ring: '#a8c7fa',
    radius: '1rem',
    fontFamily: '"GeistSans", "GeistSans Fallback", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
    composerRadius: '2rem',
    userBubble: '#222327',
    userBubbleForeground: '#e3e3e3',
  },
};

export const PRESETS: Record<ThemePreset, PresetTokens> = {
  trueforge,
  claude,
  chatgpt,
  gemini,
};

export function resolvePresetTokens(preset: ThemePreset | undefined, mode: 'light' | 'dark'): SemanticTokens {
  return PRESETS[preset ?? 'trueforge'][mode];
}
