// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         redirectUrl: "redirect_url"
 *     }
 */
export interface AuthorizeMcpServersRequest {
    /** Where to send the browser after OAuth completes. */
    redirectUrl: string;
}
