# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.list_permissions_response import ListPermissionsResponse
from ..types.permission_resource_type import PermissionResourceType
from ..types.request_error_response import RequestErrorResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawInternalClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_permissions(
        self,
        *,
        resource_ids: typing.Sequence[str],
        resource_type: PermissionResourceType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListPermissionsResponse]:
        """
        Return granted actions for each requested agent, schedule, or session id.

        Parameters
        ----------
        resource_ids : typing.Sequence[str]
            Resource ids of `resource_type` to evaluate for the caller.

        resource_type : PermissionResourceType

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListPermissionsResponse]
            Permissions keyed by resource id.
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/internal/list-permissions",
            method="POST",
            json={
                "resource_ids": resource_ids,
                "resource_type": resource_type,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPermissionsResponse,
                    construct_type(
                        type_=ListPermissionsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        construct_type(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        construct_type(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawInternalClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_permissions(
        self,
        *,
        resource_ids: typing.Sequence[str],
        resource_type: PermissionResourceType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListPermissionsResponse]:
        """
        Return granted actions for each requested agent, schedule, or session id.

        Parameters
        ----------
        resource_ids : typing.Sequence[str]
            Resource ids of `resource_type` to evaluate for the caller.

        resource_type : PermissionResourceType

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListPermissionsResponse]
            Permissions keyed by resource id.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/internal/list-permissions",
            method="POST",
            json={
                "resource_ids": resource_ids,
                "resource_type": resource_type,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPermissionsResponse,
                    construct_type(
                        type_=ListPermissionsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        construct_type(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        construct_type(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
