# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.list_pending_sandbox_environment_versions_response import ListPendingSandboxEnvironmentVersionsResponse
from .raw_client import AsyncRawSandboxEnvironmentsClient, RawSandboxEnvironmentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SandboxEnvironmentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSandboxEnvironmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSandboxEnvironmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSandboxEnvironmentsClient
        """
        return self._raw_client

    def list_pending(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListPendingSandboxEnvironmentVersionsResponse:
        """
        Returns pending environment versions for the build controller.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPendingSandboxEnvironmentVersionsResponse
            Pending versions oldest-first.

        Examples
        --------
        from trueforge_sdk import TrueForge

        client = TrueForge(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.internal.sandbox_environments.list_pending()
        """
        _response = self._raw_client.list_pending(request_options=request_options)
        return _response.data

    def progress(self, *, environment_version_id: str, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Registers or polls the snapshot build and updates version status.

        Parameters
        ----------
        environment_version_id : str
            Version row id to progress.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from trueforge_sdk import TrueForge

        client = TrueForge(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.internal.sandbox_environments.progress(
            environment_version_id="environment_version_id",
        )
        """
        _response = self._raw_client.progress(
            environment_version_id=environment_version_id, request_options=request_options
        )
        return _response.data


class AsyncSandboxEnvironmentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSandboxEnvironmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSandboxEnvironmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSandboxEnvironmentsClient
        """
        return self._raw_client

    async def list_pending(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListPendingSandboxEnvironmentVersionsResponse:
        """
        Returns pending environment versions for the build controller.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPendingSandboxEnvironmentVersionsResponse
            Pending versions oldest-first.

        Examples
        --------
        import asyncio

        from trueforge_sdk import AsyncTrueForge

        client = AsyncTrueForge(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.internal.sandbox_environments.list_pending()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_pending(request_options=request_options)
        return _response.data

    async def progress(
        self, *, environment_version_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Registers or polls the snapshot build and updates version status.

        Parameters
        ----------
        environment_version_id : str
            Version row id to progress.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from trueforge_sdk import AsyncTrueForge

        client = AsyncTrueForge(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.internal.sandbox_environments.progress(
                environment_version_id="environment_version_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.progress(
            environment_version_id=environment_version_id, request_options=request_options
        )
        return _response.data
