// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { SkillManifest } from "../../../../../../types/SkillManifest.js";

export const CreateSkillRequest: core.serialization.Schema<
    serializers.settings.CreateSkillRequest.Raw,
    TrueForge.settings.CreateSkillRequest
> = core.serialization.object({
    manifest: SkillManifest,
});

export declare namespace CreateSkillRequest {
    export interface Raw {
        manifest: SkillManifest.Raw;
    }
}
