// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as TrueHarness from "../../../index.js";

export declare namespace SessionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SessionsClient {
    protected readonly _options: NormalizedClientOptions<SessionsClient.Options>;

    constructor(options: SessionsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * List sessions (newest first by default), token-paginated. Pass `page_token` to fetch the next page, keeping the other query params constant.
     *
     * @param {TrueHarness.ListSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.BadRequestError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.list()
     */
    public async list(
        request: TrueHarness.ListSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.Page<TrueHarness.Session, TrueHarness.ListSessionsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueHarness.ListSessionsRequest,
            ): Promise<core.WithRawResponse<TrueHarness.ListSessionsResponse>> => {
                const { limit = 10, order, pageToken, startTimestamp, endTimestamp } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    order:
                        order != null
                            ? serializers.ListSessionsOrder.jsonOrThrow(order, {
                                  unrecognizedObjectKeys: "passthrough",
                                  allowUnrecognizedUnionMembers: true,
                                  allowUnrecognizedEnumValues: true,
                                  omitUndefined: true,
                              })
                            : undefined,
                    page_token: pageToken,
                    start_timestamp: startTimestamp != null ? startTimestamp?.toISOString() : undefined,
                    end_timestamp: endTimestamp != null ? endTimestamp?.toISOString() : undefined,
                };
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        "api/v1/sessions",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListSessionsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueHarness.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueHarnessError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/sessions");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueHarness.Session, TrueHarness.ListSessionsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * Create a session holding an inline agent spec. Turns are executed against this spec.
     *
     * @param {TrueHarness.CreateSessionRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.BadRequestError}
     * @throws {@link TrueHarness.UnprocessableEntityError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.create({
     *         agentSpec: {
     *             model: {
     *                 modelId: "model_id",
     *                 name: "name",
     *                 properties: {
     *                     contextLength: 1,
     *                     maxOutputTokens: 1
     *                 }
     *             }
     *         }
     *     })
     */
    public create(
        request: TrueHarness.CreateSessionRequest,
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueHarness.GetSessionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: TrueHarness.CreateSessionRequest,
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueHarness.GetSessionResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/sessions",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.CreateSessionRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetSessionResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueHarness.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 422:
                    throw new TrueHarness.UnprocessableEntityError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueHarnessError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/sessions");
    }

    /**
     * Fetch a session by ID.
     *
     * @param {string} sessionId - Session identifier.
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.NotFoundError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.get("sessionId")
     */
    public get(
        sessionId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueHarness.GetSessionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(sessionId, requestOptions));
    }

    private async __get(
        sessionId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueHarness.GetSessionResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/sessions/${core.url.encodePathParam(sessionId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetSessionResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new TrueHarness.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueHarnessError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/sessions/{sessionId}");
    }

    /**
     * Delete a session and all related turns, events, and internal state. Idempotent if already gone.
     *
     * @param {string} sessionId - Session identifier.
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.delete("sessionId")
     */
    public delete(sessionId: string, requestOptions?: SessionsClient.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(sessionId, requestOptions));
    }

    private async __delete(
        sessionId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/sessions/${core.url.encodePathParam(sessionId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.TrueHarnessError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/sessions/{sessionId}",
        );
    }

    /**
     * Update a session's inline agent spec. An empty body is a valid no-op that refreshes `updated_at`.
     *
     * @param {string} sessionId - Session identifier.
     * @param {TrueHarness.UpdateSessionRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.BadRequestError}
     * @throws {@link TrueHarness.NotFoundError}
     * @throws {@link TrueHarness.UnprocessableEntityError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.update("sessionId")
     */
    public update(
        sessionId: string,
        request: TrueHarness.UpdateSessionRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueHarness.GetSessionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(sessionId, request, requestOptions));
    }

    private async __update(
        sessionId: string,
        request: TrueHarness.UpdateSessionRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueHarness.GetSessionResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/sessions/${core.url.encodePathParam(sessionId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.UpdateSessionRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetSessionResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueHarness.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueHarness.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 422:
                    throw new TrueHarness.UnprocessableEntityError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueHarnessError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/v1/sessions/{sessionId}",
        );
    }

    /**
     * Cancel the running last turn for a session.
     *
     * @param {string} sessionId - Session identifier.
     * @param {TrueHarness.CancelSessionRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.NotFoundError}
     * @throws {@link TrueHarness.PreconditionFailedError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.cancel("sessionId")
     */
    public cancel(
        sessionId: string,
        request: TrueHarness.CancelSessionRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueHarness.CancelSessionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__cancel(sessionId, request, requestOptions));
    }

    private async __cancel(
        sessionId: string,
        request: TrueHarness.CancelSessionRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueHarness.CancelSessionResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/sessions/${core.url.encodePathParam(sessionId)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.CancelSessionRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CancelSessionResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new TrueHarness.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 412:
                    throw new TrueHarness.PreconditionFailedError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueHarnessError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/sessions/{sessionId}/cancel",
        );
    }

    /**
     * List session events as `{ turn_id, event }` across the active turn branch (newest first), including persisted events from a running tip. Each turn contributes turn.created, content events (model.message, tool.call, …), and turn.done when terminal; streaming deltas are not included. Use `page_token` to paginate backward toward older events while retaining the original branch anchor.
     *
     * @param {string} sessionId - Session identifier.
     * @param {TrueHarness.ListEventsSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.BadRequestError}
     * @throws {@link TrueHarness.NotFoundError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.listEvents("sessionId")
     */
    public async listEvents(
        sessionId: string,
        request: TrueHarness.ListEventsSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.Page<TrueHarness.SessionEventItem, TrueHarness.ListSessionEventsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueHarness.ListEventsSessionsRequest,
            ): Promise<core.WithRawResponse<TrueHarness.ListSessionEventsResponse>> => {
                const { pageToken, lastTurnId, limit = 100 } = request;
                const _queryParams: Record<string, unknown> = {
                    page_token: pageToken,
                    last_turn_id: lastTurnId,
                    limit,
                };
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        `api/v1/sessions/${core.url.encodePathParam(sessionId)}/events`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListSessionEventsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueHarness.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new TrueHarness.NotFoundError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueHarnessError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v1/sessions/{sessionId}/events",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueHarness.SessionEventItem, TrueHarness.ListSessionEventsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * List turns for a session (newest first by default), token-paginated.
     *
     * @param {string} sessionId - Session identifier.
     * @param {TrueHarness.ListTurnsSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.BadRequestError}
     * @throws {@link TrueHarness.NotFoundError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.listTurns("sessionId")
     */
    public async listTurns(
        sessionId: string,
        request: TrueHarness.ListTurnsSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.Page<TrueHarness.Turn, TrueHarness.ListTurnsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueHarness.ListTurnsSessionsRequest,
            ): Promise<core.WithRawResponse<TrueHarness.ListTurnsResponse>> => {
                const { limit = 10, pageToken } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    page_token: pageToken,
                };
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        `api/v1/sessions/${core.url.encodePathParam(sessionId)}/turns`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListTurnsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueHarness.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new TrueHarness.NotFoundError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueHarnessError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v1/sessions/{sessionId}/turns",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueHarness.Turn, TrueHarness.ListTurnsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * Create a turn within a session and stream its execution as Server-Sent Events.
     * Use `previous_turn_id` to chain to the session's last turn (defaults to `auto`).
     */
    public createTurn(
        sessionId: string,
        request: TrueHarness.CreateTurnRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<core.Stream<TrueHarness.TurnStreamingEvent>> {
        return core.HttpResponsePromise.fromPromise(this.__createTurn(sessionId, request, requestOptions));
    }

    private async __createTurn(
        sessionId: string,
        request: TrueHarness.CreateTurnRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.Stream<TrueHarness.TurnStreamingEvent>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)<ReadableStream>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/sessions/${core.url.encodePathParam(sessionId)}/turns`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.CreateTurnRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            responseType: "sse",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: new core.Stream({
                    stream: _response.body,
                    parse: async (data) => {
                        return serializers.TurnStreamingEvent.parseOrThrow(data, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        });
                    },
                    signal: requestOptions?.abortSignal,
                    eventShape: {
                        type: "sse",
                    },
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueHarness.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueHarness.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 412:
                    throw new TrueHarness.PreconditionFailedError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueHarnessError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/sessions/{sessionId}/turns",
        );
    }

    /**
     * Fetch a single turn by ID.
     *
     * @param {string} sessionId - Session identifier.
     * @param {string} turnId - Turn identifier.
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.NotFoundError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.getTurn("sessionId", "turnId")
     */
    public getTurn(
        sessionId: string,
        turnId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueHarness.GetTurnResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTurn(sessionId, turnId, requestOptions));
    }

    private async __getTurn(
        sessionId: string,
        turnId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueHarness.GetTurnResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/sessions/${core.url.encodePathParam(sessionId)}/turns/${core.url.encodePathParam(turnId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetTurnResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new TrueHarness.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueHarnessError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/sessions/{sessionId}/turns/{turnId}",
        );
    }

    /**
     * Paginated persisted events for a turn (insertion order by default).
     *
     * @param {string} sessionId - Session identifier.
     * @param {string} turnId - Turn identifier.
     * @param {TrueHarness.ListTurnEventsSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueHarness.BadRequestError}
     * @throws {@link TrueHarness.NotFoundError}
     * @throws {@link errors.TrueHarnessError}
     * @throws {@link errors.TrueHarnessTimeoutError}
     *
     * @example
     *     await client.sessions.listTurnEvents("sessionId", "turnId")
     */
    public async listTurnEvents(
        sessionId: string,
        turnId: string,
        request: TrueHarness.ListTurnEventsSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.Page<TrueHarness.SessionEvent, TrueHarness.ListTurnEventsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueHarness.ListTurnEventsSessionsRequest,
            ): Promise<core.WithRawResponse<TrueHarness.ListTurnEventsResponse>> => {
                const { limit = 25, pageToken, order } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    page_token: pageToken,
                    order:
                        order != null
                            ? serializers.ListTurnEventsOrder.jsonOrThrow(order, {
                                  unrecognizedObjectKeys: "passthrough",
                                  allowUnrecognizedUnionMembers: true,
                                  allowUnrecognizedEnumValues: true,
                                  omitUndefined: true,
                              })
                            : undefined,
                };
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        `api/v1/sessions/${core.url.encodePathParam(sessionId)}/turns/${core.url.encodePathParam(turnId)}/events`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListTurnEventsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueHarness.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new TrueHarness.NotFoundError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueHarnessError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v1/sessions/{sessionId}/turns/{turnId}/events",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueHarness.SessionEvent, TrueHarness.ListTurnEventsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * Subscribe to the live SSE stream for a turn. Pass `after_sequence_number` to resume after a disconnect (exclusive — events after this sequence number are replayed).
     */
    public subscribeToTurn(
        sessionId: string,
        turnId: string,
        request: TrueHarness.SubscribeToTurnSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<core.Stream<TrueHarness.TurnStreamingEvent>> {
        return core.HttpResponsePromise.fromPromise(this.__subscribeToTurn(sessionId, turnId, request, requestOptions));
    }

    private async __subscribeToTurn(
        sessionId: string,
        turnId: string,
        request: TrueHarness.SubscribeToTurnSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.Stream<TrueHarness.TurnStreamingEvent>>> {
        const { afterSequenceNumber } = request;
        const _queryParams: Record<string, unknown> = {
            after_sequence_number: afterSequenceNumber,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)<ReadableStream>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/sessions/${core.url.encodePathParam(sessionId)}/turns/${core.url.encodePathParam(turnId)}/subscribe`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            responseType: "sse",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        const _reconnect = async (lastEventId: string) => {
            const _reconnectResponse = await (this._options.fetcher ?? core.fetcher)<ReadableStream>({
                url: core.url.join(
                    (await core.Supplier.get(this._options.baseUrl)) ??
                        (await core.Supplier.get(this._options.environment)),
                    `api/v1/sessions/${core.url.encodePathParam(sessionId)}/turns/${core.url.encodePathParam(turnId)}/subscribe`,
                ),
                method: "GET",
                headers: { ..._headers, "Last-Event-ID": lastEventId },
                queryString: core.url
                    .queryBuilder()
                    .addMany(_queryParams)
                    .mergeAdditional(requestOptions?.queryParams)
                    .build(),
                responseType: "sse",
                timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                abortSignal: requestOptions?.abortSignal,
                fetchFn: this._options?.fetch,
                logging: this._options.logging,
            });
            if (!_reconnectResponse.ok) {
                throw new Error("SSE stream reconnection failed");
            }
            if (_reconnectResponse.body == null) {
                throw new Error("SSE stream reconnection failed: empty response body");
            }
            return _reconnectResponse.body;
        };
        if (_response.ok) {
            return {
                data: new core.Stream({
                    stream: _response.body,
                    parse: async (data) => {
                        return serializers.TurnStreamingEvent.parseOrThrow(data, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        });
                    },
                    signal: requestOptions?.abortSignal,
                    eventShape: {
                        type: "sse",
                        resumable: true,
                    },
                    reconnectionEnabled:
                        requestOptions?.stream?.reconnectionEnabled ?? this._options?.stream?.reconnectionEnabled,
                    maxReconnectionAttempts:
                        requestOptions?.stream?.maxReconnectionAttempts ??
                        this._options?.stream?.maxReconnectionAttempts,
                    reconnect: _reconnect,
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueHarness.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueHarness.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 412:
                    throw new TrueHarness.PreconditionFailedError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueHarnessError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/sessions/{sessionId}/turns/{turnId}/subscribe",
        );
    }
}
