// This file was auto-generated by Fern from our API Definition.

import type * as TrueHarness from "../../../index.js";

export interface PutModelProviderRequestModelsItem {
    /** Upstream, provider-specific identifier sent to the provider API. */
    modelId: string;
    /** Internal identifier; forms the fully qualified name `provider_name/model_name`. */
    name: string;
    properties: TrueHarness.ModelProperties;
}
