// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../../src/api/index";
import { TrueForge } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("AgentsClient", () => {
    test("get_code_snippets (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                base_url: "base_url",
                snippets: [
                    {
                        icon: "icon",
                        label_name: "label_name",
                        language: "language",
                        sample_code: { non_stream: "non_stream", stream: "stream" },
                    },
                ],
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/agents/agent_id/code-snippets")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.internal.agents.getCodeSnippets("agent_id");
        expect(response).toEqual({
            data: {
                baseUrl: "base_url",
                snippets: [
                    {
                        icon: "icon",
                        labelName: "label_name",
                        language: "language",
                        sampleCode: {
                            nonStream: "non_stream",
                            stream: "stream",
                        },
                    },
                ],
            },
        });
    });

    test("get_code_snippets (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/agents/agent_id/code-snippets")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.getCodeSnippets("agent_id");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });
});
