[program:nats]
command=/usr/local/bin/nats-server -c /var/lib/nats/nats.conf
directory=/var/lib/nats

autostart=true
autorestart=true
startretries=3

; give it a bit of time to boot before considered "up"
startsecs=5

; proper signal handling
stopsignal=TERM
stopwaitsecs=10
killasgroup=true
stopasgroup=true

; run as dedicated user if possible
user=root

; logging
stdout_logfile=/var/log/nats/nats.stdout.log
stderr_logfile=/var/log/nats/nats.stderr.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=5